### ISSUE TITLE
`C` and `alt-C` should copy selections

### ISSUE THREAD

**Issue by grtlr** [71/dance#10]
Sorry to bother you again 😉 . In regular Kakoune you can use `C` (shift-c) and `alt-C` (alt-shift-c) to copy selections to the following/previous line, which creates a multi-cursor.

> Key | Description | ALT + key | CTRL + key | g key (goto)
> -- | -- | -- | -- | --
> C | copy selection on next lines | copy selection on previous lines |  |  |

Would it be possible to add this command too? Thanks!

**Comment by 71** [comment]
Don't worry about reporting errors, it helps me take care of things I didn't think about before (and learn new commands, like I just did). Thank you for the report!

**Comment by 71** [comment]
Added in 7e4c15373b054880b65e895a178454dc38b0e454.

**Comment by 71** [comment]
Version 0.1.2 which will soon be available in the marketplace has this feature.
