### ISSUE TITLE
Add alternative shortcut for <a-i>

### ISSUE THREAD

**Issue by bm-stschneider** [71/dance#104]
There is a workaround for terminals, but not so much for vscode. As a reminder, hitting <a-i> will print ˆ on a mac instead of the inner selection popup.

**Comment by cmrn** [comment]
as per #18, the system-wide workaround on OS X is to set your keyboard to "Unicode Hex Input":

![image](https://user-images.githubusercontent.com/198225/85289163-5333df00-b4da-11ea-93b6-915e8777b518.png)

**Comment by 71** [comment]
Redirecting to the main issue for keybindings in macOS: #18.

More specifically regarding this title: custom key bindings can be added normally through VS Code, since Dance commands are regular VS Code commands.
