### ISSUE TITLE
5w or 5W does not work as expected

### ISSUE THREAD

**Issue by arturo-salinas** [71/dance#107]

**Comment by 71** [comment]
Can you provide an example where it does not work as expected, please?

**Comment by tp86** [comment]
I don't know if this is @arturo-salinas intention, but for me `w / W / e / E` don't work with counts larger than 1. For example, if line contents and cursor position are:
```
pri|vate String id;
```
after pressing `3w` I expect `id` to be selected, but instead space between `private` and `String` is selected. For starting position given above, any count before `w` will result in the same space character to be selected. 
For what I noticed, `b / B` behave correctly.

**Comment by 71** [comment]
@tp86 Thanks for your example. You're right, `wWeE` don't work properly with `"dance.selectionBehavior": "caret"`. I'm on it.
