### ISSUE TITLE
[Feature request] Using multiple commands with dance.menus

### ISSUE THREAD

**Issue by tshort** [71/dance#108]
As mentioned in #98, I implemented the Kakoune extension [kakoune-mirror](https://github.com/Delapouite/kakoune-mirror) for Dance ([gist](https://gist.github.com/tshort/7dc4457e01935e917536f32eb104a16d)). 

It uses the [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command) extension. It would be nice if the `command` argument of `dance.menus` could take an array of objects to run multiple commands. It would also be nice to be able to specify arguments on commands. With this feature, it'd be easier to implement things like kakoune-mirror.

**Comment by pomdtr** [comment]
An alternative, much more powerful (it allows vscode internal state inspection): [macro-commander](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.macro-commander)

**Comment by 71** [comment]
FYI, since `0.4.0` the `dance.run` command can be used to execute multiple commands. It's not as pretty as linearly specifying commands, but it's as powerful. In a menu, you can now write:

```json
{ "text": "...",
  "command": "dance.run",
  "args": {
    "code": [
      "await vscode.commands.executeCommand('dance.right');",
      "await vscode.commands.executeCommand('dance.objects.performSelection', { object: 'word' });",
    ],
  },
}
```
