### ISSUE TITLE
Feature Request: Support for variable in dance menus settings

### ISSUE THREAD

**Issue by pomdtr** [71/dance#109]
As discussed in #40, it would be useful to be able to access some variables when defining some custom commands (see to https://code.visualstudio.com/docs/editor/variables-reference).

**Comment by tshort** [comment]
Not sure if this helps, but the [macro-commander](https://github.com/jeff-hykin/macro-commander) extension has `injections` that can use JavaScript.

**Comment by pomdtr** [comment]
Wow, thanks for the recommendation !

**Comment by 71** [comment]
Since macro-commander can do that, I won't put high priority on this issue. If anyone wants to take care of it though (e.g. to better integrate Dance) or if other plugins somehow can't achieve what you want, feel free to re-open this.
