### ISSUE TITLE
Cannot split lines if selecting towards beginning

### ISSUE THREAD

**Issue by sebsebmc** [71/dance#117]
If I start on a line and use `K` to select lines upwards, I cannot split lines with <a-s> 

I get the error "Cannot read property 'active' of undefined"
If I use `S` to split and enter `\n` as the delimiter it works fine.

**Comment by 71** [comment]
This was fixed in 021a1fa334efcc035a9e1c1cf618358412608504 but this hasn't been released yet in the marketplace. I'll quickly draft a new minor release.
