### ISSUE TITLE
Weird thing with pipes and executables

### ISSUE THREAD

**Issue by losnappas** [71/dance#122]
Hi,

Could you tell me what I'm doing wrong? When I do

`!#eslint --version`, I get no output, but if I do `!#echo $(eslint --version)`, then I do get output. If I do `!#which eslint`, I get the path to my `.npm-global/bin` folder as expected, so why am I getting nothing in the first case?

I don't think piping stderr to stdout works correctly (`!#echo 123 >&2 2>&1` gives nothing), so I'm not sure if there's some errors going on.

**Comment by 71** [comment]
Unfortunately I'm unable to repro. I tested `eslint --version` and `echo $(eslint --version)` on both Windows and Linux, and both worked for me. Your best shot is to clone the repository and debug what's happening in [`src/commands/pipe.ts`](https://github.com/71/dance/blob/master/src/commands/pipe.ts). The `integrated.automationShell.linux` setting may be the source of the problem.

**Comment by losnappas** [comment]
After some investigation, it looks like it's only snaps that don't work. I've installed node as a snap, and eslint runs on that. Other snaps don't work either, like `#!npx --help` does nothing, nor `#!nmap --help`. Seems pretty weird, so this is probably just me.

**Comment by 71** [comment]
This sounds like an issue with snap. I found [this one](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753) which is similar.

**Comment by losnappas** [comment]
Well, I take it that it's not related to this extension, so I'll just close this.

My "workaround" is to install from an apt repo instead.
