### ISSUE TITLE
Improve the character selection behavior

### ISSUE THREAD

**Issue by tlannaax** [71/dance#124]
The current implementation of character selection behavior is kind of buggy or anti-intuitive.
The character before the cursor is selected. It seems fine if you use a line shape cursor.
But with a block or underline shape cursor, it is really weird that the character under the block or above the underline is not the one which is selected.
The other strange thing is at the beginning and end of a line. When the end of line is selected, you cursor is on the next line.

The better behavior would be to select the character after the cursor (line shape, or under the block shape, or above the underline shape), which makes things more intuitive and consistent. It is also the default behavior in vim or kak normal mode.

**Comment by 71** [comment]
Fixed in Dance 0.5 (see #102) for slightly more details.
