### ISSUE TITLE
unmapped characters are directly inputted in normal mode

### ISSUE THREAD

**Issue by tlannaax** [71/dance#125]
Usually modal editors block all input in normal mode. However, in dance the characters which are not mapped by the extension can be directly inputted in normal mode (replace the selection if there is one). 

I'm not sure if it should be thought as a bug or a feature. 
- On one hand, I tend to expect that the unmapped characters on the US-English keyboard (currently including v\<tab\>\<enter\>,'\\-+=@#^&) should do nothing in normal mode, but they in fact input and mess up my workflow upon accidentally hitting the wrong key. In the future they may get some functionality as the extension develops. For now maybe it is a good idea to block them?
- On the other hand, I found this behavior very handy because you can input non-English characters directly in the normal mode! (I believe everyone using a non-English keyboard layout or input method together with a modal editor knows the pain.) As a result, switching to non-English you are effectively in "insert" mode. I've no idea if there is a plan to develop an input method auto-switch tool as in VsCodeVim. If not, the current behavior can serve as a good enough alternative.

**Comment by tshort** [comment]
I've run into this, too. The worst issue for me is <enter>. I've been trying to think of something useful to map it to.

**Comment by 71** [comment]
Since this is configurable, I think we can think of this as a feature (although one that really gets in the way most of the time). I think the question here is whether the default keybindings should include nops for keys that don't have actions associated with them.

I'm personally favorable to that idea.
