### ISSUE TITLE
Wrong default keybinding for indentation

### ISSUE THREAD

**Issue by emilpaw** [71/dance#126]
Is there a reason why the default keybinding for indentation differs from the Kakoune one? In Kakoune it is: 
<gt> (>): indent selected lines 
and the dance default is:

![grafik](https://user-images.githubusercontent.com/39118431/101979512-ea921780-3c5d-11eb-84b5-34d2fa0b8f79.png)

**Comment by emilpaw** [comment]
Found the issue. I had changed "keyboard.dispatch": "keyCode" , because that was needed to get VSCode working correctly when Capslock is remapped to Escape on the system. Deactivating the setting does fix the problem.

**Comment by emilpaw** [comment]
Deactivating the option then removes my mapping of escape which does make dance very hard to use (weird escape key position). Any suggestion to work around this issue?

**Comment by emilpaw** [comment]
I now solved my problem by remapping the escape to capslock on a lower level using caps2esc: https://gitlab.com/interception/linux/plugins/caps2esc

**Comment by pomdtr** [comment]
You can also use the `keyboard.dispatch` setting of vscode. Setting it to keycode should resolve your issue.

**Comment by emilpaw** [comment]
Yes, that was what I had like I said in my second message. But this messes up the keybinding. It then uses the physical key location (like on a us keyboard) as the mapping, which makes it pretty confusing because the documentation of Kakoune doesn't match the actual key anymore.
