### ISSUE TITLE
workbench.colorCustomizations for incremental search highlight

### ISSUE THREAD

**Issue by danr** [71/dance#128]
Hi, first thanks for developing this extension! 

When pressing `/` and searching there is an incremental highlight but it is very dim. What is the name of this color? 

I cannot find it by reading the source code.

**Comment by 71** [comment]
Hey Dan!

The incremental search with `/` actually creates new selections for matching results, but since a prompt is shown to enter the RegExp the selection is considered inactive; the highlight color is therefore controlled by `editor.inactiveSelectionBackground`.
