### ISSUE TITLE
Feature request: User modes

### ISSUE THREAD

**Issue by tshort** [71/dance#129]
Here's how it works in Kakoune:

https://github.com/mawww/kakoune/wiki/Implementing-user-mode

**Comment by 71** [comment]
Interesting idea. I don't think it would be too hard to implement, but it won't be trivial either. On top of my head, we need:
- [ ] Make mode-specific settings more generic (`dance.normalMode.lineHighlight` -> `dance.modes: normal: lineHighlight`).
- [ ] Change `Mode` from being an `enum` to any string.

Regarding that last point, I guess a few other things need to be done, eg specifying the default mode and what to do when not enough modes are given.

In terms of keybindings, this will be trivial. But I'm not sure how some things will behave, eg changing selections. I'm guessing all modes will behave like `normal` but with different names?

**Comment by 71** [comment]
[This is implemented in 0.5](https://github.com/71/dance/blob/2d38438e15724f13cb2896f39b56edbaa6eb97ac/README.md#custom-modes). Note that all modes, including `normal` and `insert`, are custom (which is slightly different from Kakoune IIUC).
