### ISSUE TITLE
Visual cue to distinguish modes

### ISSUE THREAD

**Issue by timjs** [71/dance#13]
In vanilla Kakoune and also in Dance I tend to mix up which mode I'm in. I know the status bar shows me "Normal" or "Insert", but it is usually far away from the cursor, where my eyes are, and I have to search for the text between all the other information VSCode shows in the status bar.

I love how in Vim you can spot the difference just by looking at the cursor: a block for normal mode, and a line for insert mode. However, this is not an option for Dance, because of the (very well founded!) choice to support zero width selections.

I was thinking about other ways to visually distinguish normal mode and insert mode. Till now, I've come up with two ideas:

* Change the way the current line is highlighted:
    * while in insert mode highlight it: `"editor.renderLineHighlight": "line"`
    * while in normal mode remove the highlighting: `"editor.renderLineHighlight": "none"`
* Change the color of the status bar (don't know if this is easily doable).

What do you think of these options?

**Comment by 71** [comment]
Hey, and thanks for the feedback!

I also find the difference between the two modes too hard to notice and often try to run commands in normal mode and vice-versa. However anything that changes settings is slow, and not the best user experience (in some cases it will create a `.vscode/settings.json` file in the current workspace).  
I initially changed the highlighting of the current line through decorations but deactivated this feature due to a bug. I actually discovered yesterday that the bug originated from somewhere else so I can try working on this again, but I'm not sure the rendering will be much more obvious. I'm welcome to hearing more ideas.

FYI changing the color of the status bar is possible, but also requires changing user preferences, so it has the problems I cited above.

**Comment by 71** [comment]
I just noticed that we can change the line cursor from `Line` to `LineThin`. The difference is very subtle though.

![image](https://user-images.githubusercontent.com/7189784/69103954-10eb8080-0a67-11ea-8544-6ef52bd195b1.png)
![image](https://user-images.githubusercontent.com/7189784/69103962-1943bb80-0a67-11ea-8301-d281e31e56f0.png)

**Comment by 71** [comment]
There are several other changes we can make:

Changing the border color:
![image](https://user-images.githubusercontent.com/7189784/69104483-9faccd00-0a68-11ea-9909-95c322d9d4a4.png)

Changing the background color:
![image](https://user-images.githubusercontent.com/7189784/69104510-b8b57e00-0a68-11ea-88fc-3a3a11b6806f.png)

If we do this (and I'm completely okay with that), we need a change that's obvious enough to notice and that's consistent across all editors (support for dark mode, light mode, high contrast, custom themes).

**Comment by timjs** [comment]
Good to know I'm not the only one suffering to remember in which mode I'm working 😆 

The difference between a thin and a thick cursor line is too subtile indeed. Let's not go that way.

For my understanding:
* Turning line highlighting on/off makes UX slow but changing the background colour by hand doesn't suffer from the same performance lags?
* Is it possible to change the background colour to a colour value provided by the current theme? I did a quick scan of the [theming options](https://code.visualstudio.com/api/references/theme-color) but did not find a way to do this. Coming up with our own background or border colour will for sure bit someone using a theme we did not anticipate on.

**Comment by timjs** [comment]
Another idea:

* Change the cursor blinking mode:
    * `solid` in normal mode
    * `blink` (or `smooth`) in insert mode

**Comment by 71** [comment]
> Turning line highlighting on/off makes UX slow but changing the background colour by hand doesn't suffer from the same performance lags?

Any change to the user preferences (e.g changing the theme, changing the accent color of the status bar) is slow. However we can apply "decorations" to the editor, which are somewhat limited but much faster. Those can be used to change the background or border color of a line, for instance.

> Is it possible to change the background colour to a colour value provided by the current theme? I did a quick scan of the theming options but did not find a way to do this. Coming up with our own background or border colour will for sure bit someone using a theme we did not anticipate on.

It is possible by using decorations. But we'd need a subtle, yet clear color to distinguish the two modes.

> Change the cursor blinking mode

It looks like changing the blinking mode will also slow things down.

**Comment by timjs** [comment]
I think the only way we can choose a subtle, yet clear colour is to use one of the [predefined theme colours](https://code.visualstudio.com/api/references/theme-color).

I'd say we just decorate the current line with the theme background colour `editor.lineHighlightBackground` and possibly the border of the current line with `editor.lineHighlightBorder`. Although I think the background colour would be enough.

**Comment by 71** [comment]
I tested this with a few colors:

#### `editor.hoverHighlightBackground` (multiple selections on the same line increase opacity)
![image](https://user-images.githubusercontent.com/7189784/69233095-9026a480-0b8c-11ea-8831-0e99fdce7a3d.png)

#### `editor.hoverHighlightBackground` (multiple selections on the same line **do not** increase opacity)
![image](https://user-images.githubusercontent.com/7189784/69233614-7d609f80-0b8d-11ea-8af9-86dead2506e9.png)

#### `editor.selectionHighlightBackground` (multiple selections on the same line **do not** increase opacity)
![image](https://user-images.githubusercontent.com/7189784/69233742-c44e9500-0b8d-11ea-9d4d-ee5f59eb71a0.png)

#### Insert mode
![image](https://user-images.githubusercontent.com/7189784/69233640-8d787f00-0b8d-11ea-8cf9-d5732e4f9d2b.png)

#### Insert mode (main selection is empty)
![image](https://user-images.githubusercontent.com/7189784/69233692-ad0fa780-0b8d-11ea-988f-a799707ac463.png)

### Some more words
In my case, `editor.lineHighlightBackground` doesn't change anything.

I personally have a strong preference for `editor.hoverHighlightBackground`. In light+ (because why not), this looks like this.

![image](https://user-images.githubusercontent.com/7189784/69233968-450d9100-0b8e-11ea-8f8a-c944e252a365.png)

versus insert mode

![image](https://user-images.githubusercontent.com/7189784/69234006-59ea2480-0b8e-11ea-904b-f44cdbd1f949.png)

**Comment by timjs** [comment]
Then `editor.hoverHighlightBackground` it is!

Do you think it is better to have a highlighted background during normal mode or insert mode? My first thought was during insert mode, because selections would pop out more.

**Comment by 71** [comment]
Oh, you're right about that!

I personally went with the highlight on normal mode because IMO, insert mode is closer to "normal editing" and therefore should have a color scheme closer to "normal VS Code," but making selections pop out more by inverting this choice is a very good alternative.

**Comment by timjs** [comment]
I understand your reasoning, but after trying out the new version I really think enabling the highlight in insert mode is cleaner.

In Noctis Lux for example, it is quite hard to keep track of the difference between a selection, an active line and a search hit:
![Schermafbeelding 2019-11-20 om 15 43 06](https://user-images.githubusercontent.com/1083819/69248363-74cb9180-0bac-11ea-867a-647ab2a3606c.png)

**Comment by timjs** [comment]
And then just use the `editor.lineHighlightBackground`. It is intended as the background of a line when editing and softer than `editor.hoverHighlightBackground`:
![Schermafbeelding 2019-11-20 om 15 49 26](https://user-images.githubusercontent.com/1083819/69248895-574af780-0bad-11ea-943b-cbf434e10fae.png)

**Comment by timjs** [comment]
Selecting a whole line using `x` also looks funny now:
![Schermafbeelding 2019-11-20 om 15 54 03](https://user-images.githubusercontent.com/1083819/69249330-fd96fd00-0bad-11ea-805f-86ccf86011e7.png)

**Comment by 71** [comment]
`editor.lineHighlightBackground` doesn't seem to be set for the default dark theme, so in my case it doesn't change anything. We could make this a preference.

For me `x` behavior makes sense since the selection ends on the second line, but if you think it's better to act like it doesn't, I'll add a special case for it.

I'll try to push a change that goes in your way. A preference could be added for this too.

**Comment by timjs** [comment]
`editor.lineHighlightBackground` is not set for the default dark theme indeed, but `editor.lineHighlightBorder` is, see below. Means we should set both, in case a theme only sets on of the two.

![Schermafbeelding 2019-11-21 om 10 53 39](https://user-images.githubusercontent.com/1083819/69327053-30440280-0c4d-11ea-8df9-fe36d37f2375.png)

Making this a preference is fine with me.

About the `x` behaviour: I'm totally fine with the way selections are made. It is perfectly clear what the selection is, and that the end-of-line is included. Please do not make a special case for it, it will only complicate the code. I only raised it to make a point for highlighting the current lines in insert mode instead of normal mode, because I think the background colour interferes with the selection colour. Because selections are not possible in insert mode, this problem will never occur.

**Comment by hedning** [comment]
Would it make sense to use a `block` cursor when there's no selection in normal mode? I've been experimenting with a kakoune like system in emacs (after trying vscode with dance) and quickly hit the same problem, using a block cursor on empty selections stopped the mistakes for me at least.

Ie. use a block cursor as a pseduo-selection. The main problem I can see with this is deciding how commands should interact with empty selections. Eg. should `backspace` kill the character within the block or the char behind it etc.

**Comment by timjs** [comment]
Using a block cursor would imply that there is always a selection of 1 character, which does not fit nicely with the VSCode of working.

- How would we represent the selection of a whole line? Now it is clear, because the line cursor is on the start of the next line.
- What should we do when the cursor is past the last char of a line? Now it it just a line. Otherwise, would it select the “end of line” implicitly or not? (Kakoune does this.)
- The usage of `x` [becomes inconsistent](https://github.com/mawww/kakoune/issues/2590). When the cursor is on an empty line or at the end of a line, you should just use `d` to delete the line end. `xd` would delete two lines. Using a line cursor, `xd` always deletes one line. 

We still could try to swap from a thick line in normal mode to a thin line cursor in insert mode. Although it is subtiel, I found out my eyes notice the difference quickly. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hedning** [comment]
I mocked up a prototype: https://github.com/hedning/dance/commit/9c78ba53c2c83f006f8a64a0e8b3c662faa2075b (here's a compiled version: [dance-0.1.6.vsix](https://www.jottacloud.com/s/070376f22ac98ff431096b488243d5d0936))

To be clear, I'm suggesting only using a block cursor when there's no selection. Ie. the case where it's currently not clear if you're in insert or normal mode.

> Using a block cursor would imply that there is always a selection of 1 character

Yes, and there's certainly a few edge cases which are trickier with that model. Eg. should `b` extend the whole cursor? And the first `shift+l` would need to move two chars, and how would `ctrl+backspace` work etc.?

The upshot is two visually distinct modes, insert and selection. That might just be me though, I'm really accustomed having line cursor mean insert mode, and doubt any coloring etc. will do as good as showing a selection/block.  

> How would we represent the selection of a whole line?

In that case there's a non-empty selection, so a line cursor would be used.

>  What should we do when the cursor is past the last char of a line?

I'd guess implementation wise it's easiest to treat it as a selection of the newline char, so eg. `d` would merge the lines (like kakoune). However I don't see anything wrong with having eg. `d` not do anything at the end of line either. The idea that newlines are regular characters doesn't really make much sense to me tbh.

> `xd` would delete two lines

We'd get a selection, so would use a line cursor after `x`. Should work the same.

**Comment by 71** [comment]
About using a block character -- why not, but I want this behind an optional preference, and this isn't high priority for me (but I'll try to accept a PR that implements it if you want to submit one).

It will definitely require some changes in the existing code, but something nice about this is that this is the way Kakoune originally works, so this option will increase compatibility with Kakoune, and any of the choices we make regarding its implementation can be made by looking at the way Kakoune does it.

Regarding the line highlight -- I've been using the current config for a few days now as a long time Vim user (so I'm used to looking at the cursor to find out if I'm in normal or insert), and I no longer confuse the two modes. I do understand your preference, and suggest putting this behind a user preference. How about adding `dance.{normal,insert}Mode.lineHighlight` which can be `false`, an hex color, or a theme color name?

**Comment by timjs** [comment]
I like your suggestion on the `dance.{normal,insert}Mode.lineHighlight` option!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timjs** [comment]
Thanks for implementing this! I'm using it with the options:
```
    "dance.normalMode.lineHighlight": null,
    "dance.insertMode.lineHighlight": "editor.lineHighlightBackground",
```
and I really like the outcome. Selections are clear in normal mode, and switching to insert mode gives me cues of where my cursors are. Awesome!

**Comment by 71** [comment]
Note: `lineHighlight` is ignored now, and `decorations.backgroundColor` should be used instead (see https://github.com/71/dance/issues/204#issuecomment-934222172 for an example).
