### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by brianking** [71/dance#131]
Thank you for being part of the Open VSX community by adding your extension(s) to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extension(s). To ensure uninterrupted service, please create an [Eclipse account](https://accounts.eclipse.org/user/register) (or use an existing one if you have it) and sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) on or before January 8, 2021. If not signed by that date, your extension(s) will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extension(s) will then be re-activated.

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

See also:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by 71** [comment]
[Done](https://accounts.eclipse.org/users/ggeis/eca).
