### ISSUE TITLE
Numpad/keypad bypasses Dance and inputs text in normal mode

### ISSUE THREAD

**Issue by tmewett** [71/dance#137]
All keypad numbers and symbols input text. This means you can't use `*`, `/`, and `.` commands or number/repeat commands from the keypad.

**Comment by 71** [comment]
It looks like these keybindings have their own names (e.g. `Keypad0`). A simple fix would be to duplicate all exported bindings with numbers and these symbols with the `Keypad` prefix. In the meantime you can do it manually in `keybindings.json`.
