### ISSUE TITLE
Feature request: option for `w` and `b` to move by/select whole words instead of to the start of a new word.

### ISSUE THREAD

**Issue by nothingnesses** [71/dance#138]
I used [this plugin](https://github.com/alexherbo2/word-select.kak/blob/master/rc/word-select.kak) on Kakoune and have found it more convenient than Kakoune's normal behaviour. AFAIU, the plugin makes it such that the word navigation keys `w` and `b` move/select whole words (excluding trailing whitespaces) instead of moving to/selecting to the end/start of the current word (which is instead done with `W` and `B`, and which also excludes trailing whitespaces). It would be nice if there was an option to enable the same behaviour for Dance.

I've included some example expected behaviours if this hypothetical option was enabled in Dance. For each example, the first row is the buffer's state before input, second is the input (in normal mode), and the third is the buffer's state after the input. `|` is where the cursor is, `[` and `]` indicates the start and end of selection. These assume caret selection is enabled.

1.
`word_a wor|d_b word_c`

`w`:

`word_a [word_b]| word_c`

2.
`word_a wor|d_b word_c`

`b`:

`word_a |[word_b] word_c`

3.

`wor|d_a word_b word_c`

`ww`:

`word_a [word_b]| word_c`

4.

`word_a word_b wor|d_c`

`bb`:

`word_a |[word_b] word_c`

5.

`word_a wor|d_b word_c`

`W`:

`word_a wor[d_b]| word_c`

6.

`word_a wor|d_b word_c`

`B`:

`word_a |[wor]d_b word_c`

7.

`wor|d_a word_b word_c`

`WW`:

`wor[d_a word_b]| word_c`

8.

`word_a word_b wor|d_c`

`BB`:

`word_a |[word_b wor]d_c`

**Comment by 71** [comment]
Looking at it, it looks like it's implemented by invoking existing Kakoune commands. I spent some time trying to replicate this and some changes were needed, but in `0.4.2` you can have this kind of keybinding:

```json
{
  "key": "w",
  "command": "dance.run",
  "args": {
    "code": [
      "const editor = vscode.window.activeTextEditor,",
      "      prev = editor.selections;",

      "try {",
      "  await dance.execute('.objects.performSelection', { object: 'word', action: 'select' });",
      "} catch (e) {",
      "  if ((e?.message ?? '') !== 'no selections remaining') throw e;",
      "}",

      "if (editor.selections.every((x, i) => x.isEqual(prev[i]))) {",
      "  await dance.execute(",
      "    ['.search', { input: '\\\\w' }],",
      "    ['.objects.performSelection', { object: 'word', action: 'select' }]);",
      "}",
    ],
  },
  "when": "editorTextFocus && dance.mode == 'normal'"
},
```

And similar keybindings with `WbB` (replacing the arguments of `objects.performSelection` as needed). Unfortunately there is a bug in the above code that will lead to "no selections remaining" being printed in some cases, but I haven't found out why yet
(and you can probably work around this).

In the future I'd like to make keybindings scriptable and to improve the scripting API, but for now this will have to do.

**Comment by nothingnesses** [comment]
@71 Thanks. I'm also not sure what's causing the "no selections remaining" bug. FWIW, I found out that adding a property `inner: 'true'` to the `.objects.performSelection` argument object seems to make the `w` key work how I expected it to (so it selects to the end of the current word instead of to the start of the next word).

I can't figure out what to do for the `b` key though, there doesn't yet seem to be an action that selects the whole word, but moves the cursor to the start of the word rather than the end like `select` does. I'm aware of the `selectToStart` command which selects from the current cursor position to the start of the current/nearest word, so as a work-around, I tried adding:

```JSON
	{
		"key": "b",
		"command": "dance.run",
		"args": {
			"code": [
				"const",
				"  editor = vscode.window.activeTextEditor,",
				"  prev = editor.selections;",
				"try {",
				"  await dance.execute('.objects.performSelection', { object: 'word', action: 'select', inner: 'true' });",
				"  await dance.execute('.objects.performSelection', { object: 'word', action: 'selectToStart', inner: 'true' });",
				"} catch (e) {",
				"  if ((e?.message ?? '') !== 'no selections remaining') throw e;",
				"}",
				"if (editor.selections.every((x, i) => x.isEqual(prev[i]))) {",
				"  await dance.execute(",
				"    ['.search', { input: '\\\\b' }],",
				"    ['.objects.performSelection', { object: 'word', action: 'select', inner: 'true' }]);",
				"    ['.objects.performSelection', { object: 'word', action: 'selectToStart', inner: 'true' }]);",
				"}",
			],
		},
		"when": "editorTextFocus && dance.mode == 'normal'"
	},
```
But this doesn't seem to work. It's supposed to select the current word (moving the cursor to the end of it), then select to the start of it, which should select the whole word but move the cursor to the start rather than the end. It'd be an ugly hack if it'd worked, so ideally there should be an action dedicated to it, right?

**Comment by 71** [comment]
I think I know what the issue is. First of all, to search backwards you should use `dance.search.backwards` with input `\\w` (the input is a RegExp). Second of all, you can use `dance.selections.{backward,forward}` to change the direction of the selections.

```json
{
  "key": "b",
  "command": "dance.run",
  "args": {
    "code": [
      "        const editor = vscode.window.activeTextEditor,",
      "              prev = editor.selections,",
      "              commands = [['.objects.performSelection', { object: 'word', action: 'select', inner: true }],",
      "                          ['.selections.backward']];",
      "",
      "        try {",
      "          await dance.execute(...commands);",
      "        } catch (e) {",
      "          if ((e?.message ?? '') !== 'no selections remaining') throw e;",
      "        }",
      "",
      "        if (editor.selections.every((x, i) => x.isEqual(prev[i]))) {",
      "          try {",
      "            await dance.execute(['.search.backwards', { input: '\\\\w' }], ...commands);",
      "          } catch (e) {",
      "            if ((e?.message ?? '') !== 'no selections remaining') throw e;",
      "          }",
      "        }"
    ]
  },
  "when": "editorTextFocus && dance.mode == 'normal'"
}
```

Unfortunately I did some debugging and `no selections remaining` still happens in that case and worse yet, it somehow prevents the code from working correctly. I have an idea of where the issue comes from (some off by one errors when handling selections that does not seem to happen in `character` mode) but I haven't been able to fix it yet.

**Comment by 71** [comment]
With Dance 0.5 available (not yet in the marketplace while we find remaining bugs), this should be much easier to implement, with per-selection changes. Supporting `Character` selection modes will be tougher, though.

**Comment by 71** [comment]
Here's a try at it using the Dance API (it's only for `w`, but you can probably modify it to support other variants fairly easily):

```ts
Selections.update((text, selection) => {
  // Note: the condition below must be tweaked in character mode.
  if (text.length === 0) {
    const start = moveWhile.backward((c) => /\w/.test(c), selection.start),
          end = moveWhile.forward((c) => /\w/.test(c), selection.end);

    return Selections.from(start, end);
  }

  return wordBoundary(Direction.Forward, selection.end, false, 7 /* CharSet.Word */);
})
```
