### ISSUE TITLE
Numeric arguments to commands do not behave as expected

### ISSUE THREAD

**Issue by endowdly** [71/dance#139]
**Numeric arguments (mostly) behave as expected with movements!**
However, commands given numeric arguments do not.

xs\w+\b\<Enter\>

    |public| |static| |int| |ColorCode|(|string| |color|)

2<a-)>
<a-(><a-(>

expected:

    |public| |static| |int| |ColorCode|(|string| |color|)

actual:

    |color| |public| |static| |int|(|ColorCode| |string|)

Also, say I yank the selection.

xy8p

expected: 8 copies of the line following the line
actual: 1 copy

Is this intended?

**Comment by 71** [comment]
Hey there, and sorry for the delay. The rewritten version of Dance, available on `master` but not yet in the marketplace, no longer has these issues.

Thanks for the report!
