### ISSUE TITLE
Some keybindings are incorrectly generated

### ISSUE THREAD

**Issue by timjs** [71/dance#14]
Some keybindings are set to `unknown` by VSCode. This probably has to do something with the [generate script](https://github.com/71/dance/blob/master/commands/generate.ts) and the [yaml source](https://github.com/71/dance/blob/master/commands/commands.yaml).

Till now I've found these keys do not work out of the box (including their alt-counterparts):
* Search and friends (/, ?)
* Objects and friends ([, ], {, })
* Indentation (<, >)

**Comment by 71** [comment]
I've worked a bit on this tonight and fixed most commands, but since I don't have a Qwerty keyboard I can use, there are commands I simply don't know how to get. Can you try finding the commands for `&`, `[`, `]`, `{` and `}`, please? Better yet, if you could find the right keybindings for all commands with `unknown`s in them, I will make sure to add them correctly!

**Comment by timjs** [comment]
Below you'll find all the keybindings which are set to `[shift+][alt+]unknown` on my system (macOS 10.14.6, VSCode 1.40.1, Qwerty keyboard).

![Schermafbeelding 2019-11-19 om 10 50 24](https://user-images.githubusercontent.com/1083819/69136105-8e8cac00-0aba-11ea-8492-447c1d10166d.png)
![Schermafbeelding 2019-11-19 om 10 50 35](https://user-images.githubusercontent.com/1083819/69136107-8e8cac00-0aba-11ea-9da7-8472b3e2145a.png)
![Schermafbeelding 2019-11-19 om 10 50 46](https://user-images.githubusercontent.com/1083819/69136109-8f254280-0aba-11ea-9cd4-aef85ab6e4fc.png)
![Schermafbeelding 2019-11-19 om 10 50 54](https://user-images.githubusercontent.com/1083819/69136110-8f254280-0aba-11ea-9577-559bb6b0141e.png)

From top to bottom, they should be assigned to:
```
s+7
a+,
s+.
a+0
a+9
/
s+'
]
[
s+`

s+]
s+[
s+/

s+a+7
s+,
s+a+.
s+a+-
s+a+0
s+a+9
a+/
a+]
a+[

s+a+]
s+a+[
s+a+/
```

PS I assumed `Dance: Deindent (including incomplete indent)` is the default `>` and  `Dance: Deindent` the alternative.

**Comment by 71** [comment]
Thanks for the help! 8fb3f3ffd758e498c4e0553e9414b5ccb7130b26 should fix it.
