### ISSUE TITLE
Dance 0.5.0 wishlist

### ISSUE THREAD

**Issue by 71** [71/dance#141]
Dance 0.5.0 [is coming](https://github.com/71/dance/tree/wip). It's basically rewritten from scratch to be nicer to work on, and to add many more features that work well together.

It's still very much a work in progress, but I'd like to know what features you'd like to see in this release, and more importantly what you'd like to do with the upcoming features.

At the source-code level, a new API is introduced, which is very easy to document and test. Having more tests will hopefully make Dance more stable in the long term. Also, the root `commands` directory is removed, and instead all commands are defined directly in `src/commands` using [`JSDoc`](https://jsdoc.app). Now, there is a single source of truth.

At the user level, a lot of things will change too:
- Status bar items are more useful.
- Most commands either take arguments or are implemented by passing arguments to existing commands.
- The "character" selection behavior is now designed to work with `"block"` cursor styles. It will no longer mess with your selections while you're editing, so you won't have single characters highlighted when navigating your code. It should also make it easier to work with for maintainers.
- All modes are now custom. You can customize which mode is the default mode, as well as define your own modes that inherit from VS Code or from other custom modes. The default will still be the Kakoune-like `insert` / `normal` modes, but I have other things modes in mind for the future.
- A new command, `dance.run`, will be added. It will be able to run custom JavaScript code with access to the Dance API, allowing complex scripts (for instance, manipulating different selections individually).

The last thing I'd like to change is how keybindings are defined. I wanted to add a `dance.defaultKeybindings` option / context value, but unfortunately even if we set this to `false` the keybindings still appear in the command palette. As such I'd like to simple remove all default keybindings, and to add utilities in the Dance API for generating keybindings (that can then be pasted into `keybindings.json`).

Another nice thing about this solution is that it would make supporting alternative keyboard layouts and Mac easier. Unfortunately, removing default keybindings may make it harder for new users to get started.

So, any feedback?

**Comment by pomdtr** [comment]
Very curious about the new block character option, I was using the caret mode as it feels more natural in VSCode.
I was in the process of writing some fix for errors and inconveniences I encounter daily in Dance, should I wait for 0.5.0 to implement them ?

**Comment by 71** [comment]
@pomdtr I personally prefer the caret mode too, but I know some folks prefer the character mode (which is closer to Kakoune and has some nice quirks, like the fact that `d` is equivalent to Vim's `x`).  
Before, Dance updated editor selections to ensure they were never empty, and some commands behaved differently if the selection behavior was `character`. Now, Dance will translate selections when processing them internally when the behavior is `character`, so editor selections won't be updated automatically and maintainers don't have to think about it either, it should all be handled in the translation.

Yes, you should probably wait. Everything is different now. If you want to take a look, it's all in the `wip` branch. Notably, `Alt+P` is implemented in [`src/commands/edit.ts`](https://github.com/71/dance/blob/157480a896b50337d74f2fa760033a63ea2eb645/src/commands/edit.ts#L52).

No problem. Truth be told it was hard working on it lately which is why I started the rewrite to make things a little more fun.

**Comment by pomdtr** [comment]
I have some keybindings that integrate really nicely with dance and could maybe set as default behavior:

```
  {
    "key": "alt+u",
    "command": "cursorUndo",
    "when": "textInputFocus && dance.mode == 'normal'"
  },
  {
    "key": "shift+alt+u",
    "command": "cursorRedo",
    "when": "editorTextFocus && dance.mode == 'normal'"
  },
  {
    "key": "ctrl+o",
    "command": "workbench.action.navigateBack"
  },
  {
    "key": "ctrl+i",
    "command": "workbench.action.navigateForward"
  },
```

**Comment by tshort** [comment]
I'm looking forward to better/easier customizability! I'm also a fan of character mode, so if the "block" changes help that, I'm happy.

I'm not too excited about losing default keybindings. I don't mind if there's extra "junk" in the command palette.

**Comment by 71** [comment]
@tshort Do you also mind if there's an easy way to add the default keybindings to the user settings? I'm working on a single command that would automatically open the `keybindings.json` file and copy the default keybindings to the clipboard with some amount of customizability, making the transition not-so-hard.

**Comment by jcmkk3** [comment]
It may be worth taking a look at [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode) to see how they handled generating keybindings. I think that they were operating with some similar goals.

**Comment by 71** [comment]
Thanks for the pointer @jcmkk3. It looks like they also have a command that opens the settings and keybindings files and edit them with the default keybindings. They also show a welcome message with a button that can run that command, so I think I'll go this way too.

**Comment by losnappas** [comment]
Wishlist? Would like to see a `jj`/`jk` escape that is immune to vscode lag. Or maybe that's already possible? I dunno how to override the type command.

@pomdtr for `ctrl-i/o` I'd recommend the "sensible back and forward" vscode plugin. As for alt+u, I miss that _from_ Kakoune :pirate_flag:

**Comment by 71** [comment]
@losnappas I believe this will be possible with the API. It exposes the `keypress` function, so you can probably assign the following script to the key `j` in `insert` mode:

```ts
const pressed = await keypress();

if (pressed === "j") {
  await setMode("normal");
} else {
  await insert("end", "keep", () => "j" + pressed);
}
```

**Comment by darfink** [comment]
Will there be any support for registers when yanking (system clipboard not being the only option)?

**Comment by 71** [comment]
@darfink There already is support for registers when yanking. There was no support for alphabetic registers, but there were most [alternative registers](https://github.com/71/dance/blob/c6ea85dbfc5e66ca7d674040fbcc415de6f062c5/src/registers.ts#L98) like `@`, `^`, etc. Dance 0.5.0 does improve support for registers a lot, though, including per-document registers, as well as numeric and alphabetic registers.

All functions that were previously available have been ported to Dance 0.5.0. I'm now converting the old tests to the new test format, fixing bugs that arise, and adding new tests. If you'd like to try the new version and create tests for issues that may arise, please clone the `wip` branch and look at the disclaimer in `README.md`.

**Comment by 71** [comment]
I'm getting close to being done with Dance 0.5. The remaining things before releasing it are:
1. Porting all remaining tests.
2. Ensuring that they all pass.
3. Adding a few more recognized patterns for replaying history.

After this I'll probably take a break from working on Dance, but for the near-ish future I'm planning:
- For 0.5.x, to add new tests, especially regarding the history and the new API.
- For 0.6.0, improving the API, especially regarding keybindings. For now all keybindings are bundled with Dance, but for this release I'd like all keybindings to be generated with the `keybindings` API, with support for other layouts like azerty.
  * I'd like to add a compatibility mode with Kakoune, too. Many of the newer commands have a parameter to behave more like Kakoune, but can be tweaked to behave in a way that I personally prefer.
- For 0.6.x, I'll add more tests and flesh out the documentation.

And after that hopefully I'll release Dance 1.0 with a stable API and minimal bugs.

**Comment by 71** [comment]
Dance 0.5.0 has been merged to master. Please pull the changes and play with it, though there will likely be mistakes. I've been working exclusively on it for a few weeks, and during that time I wasn't able to _actually use it_ so there might still be obvious mistakes.

I'll probably upload it to the marketplace in a week or so, once I will have had some time to play with it and see what needs to be fixed.

A few unplanned things have been done for 0.5:
1. Many, many changes to tests. They should be easier to write and catch more mistakes.
2. The `view` menu was added, as well as support for `prefix` menus (used to implement `jj`) and `locked` menus (used to implement the locked view menu).
3. Errors are now displayed in the status bar. I was worried they would be too hard to notice, but I actually think it looks nice now. Plus this way they can be dismissed as soon as the user types, similarly to Kakoune.
4. I added a new "Show selections" command bound to `Enter` by default. It toggles showing the index of each selection at the end of each line.

**Comment by pomdtr** [comment]
Awesome news ! The new "Show selections" is really welcome.

Where do you us to list issues we encounter on master ? I think an issue for each minor issues would be to much.

**Comment by 71** [comment]
If the issues are new, please file them here. Otherwise, please link to an existing / new issue for them. Thanks for all your reports, I'll take a look at them when I have some time!

**Comment by 71** [comment]
- `gg`,`gk`, focus not followed issues are fixed.
- I can't reproduce, regarding `"`. Does the command start (cursor should change to `underline`, mode changes to `input`, and after pressing a key the register displays in the status bar, next to the mode name)? If not, it's likely a keybinding issue. Can you try running "select register" from the command palette? It's also possible it's due to your keyboard layout.
- I can't reproduce with `s` either. The secondary selections are quite hard to see, though (due to the theme colors), and the lines of the cursors don't always show (I believe this one is a VS Code issue).

**Comment by pomdtr** [comment]
> Edit: As for the view menu, is it possible that you already have a keybinding for spawning that menu? Now a lot of commands (including openMenu) accept an "input", and if it is not provided it will be prompted. The v keybinding should have an argument "input": "view".

Yep this was the case :)

**Comment by shekhars094** [comment]
when 0.5 will release on marketplace.?

**Comment by 71** [comment]
We still find bugs from time to time, but I think it's close to being as stable as 0.4 (if not more stable). The changes I made to history recently had me remove the command "Jump to last modification", so I have to re-implement it and then it should be a few days until the release.

**Comment by 71** [comment]
II added two "unexpected features" to Dance 0.5, so I'll wait a little bit longer in case they cause issues:
1. Display warnings in the editor when some selections are out of view.
2. History in prompts (i.e. pressing `Up` or `Down` will show previous inputs in RegExp/code inputs).

**Comment by 71** [comment]
Dance 0.5 has been published [in the marketplace](https://marketplace.visualstudio.com/items?itemName=gregoire.dance).
