### ISSUE TITLE
Cursor moves out of visible window area

### ISSUE THREAD

**Issue by andycraig** [71/dance#15]
Thank you very much for making this and putting it on the marketplace!

I've found that when in normal mode, moving the cursor off the top or bottom of the window does not cause the window to scroll.

To reproduce:

1. Have enough text in the file that the bottom of the file cannot be seen
1. Be in normal mode (not insert mode)
1. Keep pressing <kbd>j</kbd> until the cursor moves below the last visible line
1. Observe that the window does not scroll, and the cursor is no longer visible

The same applies when the top of the file is not visible and I move the cursor to the start of the file using <kbd>gg</kbd>.

I've disabled all extensions except Dance.

I've observed the issue on Linux and Windows.

Version info (Linux):

Dance: 0.1.4 
Ubuntu 18.04.2 LTS
VSCode:
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-70-generic

Thank you, and let me know if there's any other info I can provide etc.!

**Comment by timjs** [comment]
Heaving the same issue here.

**Comment by 71** [comment]
I just realized that the whole `move` implementation (left, right, top, down) is broken in various other ways... I've started working on a fix but it's going to take some time. In any case, thanks for the report.

**Comment by andycraig** [comment]
No problems, I look forward to the fix whenever it’s ready :) Thanks again for all your work on this!

**Comment by 71** [comment]
Commit bb84bfd3f1d6b6307770b385de465d6347048c43 fixes movements to be the same as Kakoune's!

**Comment by andycraig** [comment]
Wow, that was a lot quicker than I expected! Thank you!

**Comment by timjs** [comment]
This still happens when using goto commands like `gg` or `ge`, when using the new `n` or `a+n` searches or just using search itself `/` or `a+/`!
