### ISSUE TITLE
quick multi cursor 

### ISSUE THREAD

**Issue by lauccode** [71/dance#152]
Kakoune is expected to search a word with multi-cursor.
You can select a word and put the selection in search buffer with ' * '
After, you can mutli-select the next identical word with <shift+n>.

In Dance, is there a way to do the same ? We can copy a word and after search with < / > and paste it but it is very long to do compare to Kakoune.

**Comment by 71** [comment]
Does `*<s-n>` not work for you? It's also implemented in Dance. I just tried it and it works both in 0.5 (on `master`) and in 0.4 (in the marketplace).

**Comment by lauccode** [comment]
Not work for me. if I press ' * '  it replaces the word with ' * '.
But ok it is good if already implemented. I will look to find why it is not working for me.
Thanks

**Comment by 71** [comment]
What keyboard layout do you use? By default, Dance uses `Shift+8` for `*`, since in VS Code we can't directly bind to the key `*`. Try opening the command palette and searching for `Dance: Search current selection (smart)`, the key it is bound to will be shown on the right.

**Comment by lauccode** [comment]
I can see "Shift + _" Recently used

**Comment by 71** [comment]
Strange. Are you on Dance 0.5 or 0.4 (if you cloned the repository it's 0.5, otherwise it's 0.4)? On 0.4, the name is "Search current selections (smart)"

**Comment by lauccode** [comment]
Plug in is automatically installed by vscode(1.55.2) and name is "Search current selections (smart)".
It seems to be 0.4

**Comment by 71** [comment]
Then that's 0.4. That command "Search current selections (smart)" did not work (instead of `*`)?

**Comment by lauccode** [comment]
it is working if I use "Search current selections (smart)" instead of than '*'

**Comment by 71** [comment]
I think it's a keyboard layout issue. I suggest you bind the command to the `*` key in the keybindings UI in VS Code. It will automatically pick the key that corresponds to your keyboard layout.

**Comment by lauccode** [comment]
I tried, it is working like that.
Thanks
