### ISSUE TITLE
new go to definition target

### ISSUE THREAD

**Issue by jbytes1027** [71/dance#157]
I think a goto definition target would be very useful and perfectly fits into the entire purpose of dance being able to use modern ide features from vscode.

**Comment by pomdtr** [comment]
This is already supported: you can add custom commands using the `dance.menus` settings.

**Comment by 71** [comment]
+1 @pomdtr

I personally have a menu bound to `tab` that can go to definition, search symbols, jump to file, open the terminal, etc.
