### ISSUE TITLE
implement kakoune style autocomplete

### ISSUE THREAD

**Issue by jbytes1027** [71/dance#158]
I think the kakoune style of autocomplete where selections are auto inserted is much better than the default vscode behavior where a confirmation key like enter or period has to be pressed, aka tab completion with suggestions.

**Comment by 71** [comment]
I'm afraid extension authors don't have any access to auto-completions, so (using the built-in VS Code completions) this is impossible.

In theory, we could use [`vscode.executeCompletionItemProvider`](https://code.visualstudio.com/api/references/commands#commands), but this would also mean:
- We must query the completions ourselves any time a completion might be inserted.
- We must provide a custom menu for completions.
- We must provide the Kakoune-like autocompletions when the selected completion changes.

This sounds like a lot of work, and I'm not sure the experience in the end would be better than the native VS Code completions. In my opinion this is out of scope, but you could always make your own extension for it.
