### ISSUE TITLE
Cursor gets stuck at end of document

### ISSUE THREAD

**Issue by andycraig** [71/dance#16]
It seems like the cursor can get 'stuck' at the end of a document while in normal mode. I don't know exactly what triggers it; it only seems to happen sometimes.

Here's a set of steps to reproduce. It's a bit of a strange sequence but it was the minimal set of steps I could find.

1. Open a new document, and do the following key presses:
1. <kbd>i</kbd> (enter insert mode)
1. <kbd>a</kbd>
1. <kbd>Enter</kbd> (document should now be 'a' followed by an empty line)
1. <kbd>Esc</kbd> (back to normal mode)
1. <kbd>k</kbd> (cursor is now at the start of the document)
1. <kbd>k</kbd> (even though the cursor is already at the start of the document, this seems to be necessary)
1. <kbd>j</kbd>
1. <kbd>j</kbd> (cursor is now at the end of the document)
1. <kbd>k</kbd>

This last <kbd>k</kbd> doesn't move the cursor up, and it is now 'stuck'. If the cursor becomes stuck on a line that does contain text, it can't be moved left with <kbd>h</kbd> either.

Entering insert mode or jumping (e.g., <kbd>gg</kbd>) makes the cursor 'unstuck' and free to move again.

Thanks again!

Dance: 0.1.4
Ubuntu 18.04.2 LTS
VSCode:
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-70-generic

**Comment by 71** [comment]
Commit bb84bfd3f1d6b6307770b385de465d6347048c43 should fix this.

**Comment by andycraig** [comment]
Great, thank you!
