### ISSUE TITLE
FR: add keep not matching

### ISSUE THREAD

**Issue by BeastyBlacksmith** [71/dance#162]
Thats `<a-K>` in Kakoune

**Comment by 71** [comment]
This is also supported in Dance (`a-K` as well). Is it not working for you?

FYI, `a-K` in Dance uses `dance.run`, which is a little different from Kakoune. If you want to filter by regexp, type `/<regexp>`. If you want to filter using a JavaScript expression, just type the expression.

**Comment by BeastyBlacksmith** [comment]
seems it does work. I just couldn't find it in the command pallette
