### ISSUE TITLE
Select all files

### ISSUE THREAD

**Issue by BeastyBlacksmith** [71/dance#163]
Is there a way to select all text in all files in the project or a folder like the vscode search and replace (`c-F`)?

I could get a page with all the results, when clicking on `open in editor` and I also could make changes, but I could not get it to apply these changes back to the files (instead it prompted me to save a code.search file).

**Comment by 71** [comment]
I'm not sure what you want to do exactly. Can you explain again, please?

**Comment by BeastyBlacksmith** [comment]
I am about to write a macro the executes several commands, such that I can do it file by file.

Instead I would like to make a selection across all files (lets say in the `src` folder) and the execute the commands onyl once, but probably vscode doesn't support multicaret selection across files.

**Comment by 71** [comment]
Indeed, there are two issues here:
1. Dance is designed to work on a per-editor basis. There is no support at all for actions that work on multiple editors at the same time.
2. The VS Code API for extensions can only operate on editors that are visible to the user (the contents must be visible; having it open in an inactive tab is not enough AFAIK).

This makes it pretty hard to do. Nonetheless, some VS Code APIs exist that allow [per-workspace changes](https://code.visualstudio.com/api/references/vscode-api#workspace.applyEdit). There is no support for this at the Dance side, though with Dance 0.5 and `dance.run` you can make scripts that use the VS Code API.

Alternatively, you could have a script that iterates over all files, opening them and modifying them one by one. This will open all the files in (new) editors, though.

**Comment by BeastyBlacksmith** [comment]
Actually my experiment with vscode search and replace looked like a decent API if it worked.

This is what I got after clicking `open in editor`
![Bildschirmfoto vom 2021-05-26 18-15-11](https://user-images.githubusercontent.com/18145188/119695508-8602f780-be4e-11eb-8bfd-e35eb85c6a6e.png)

This has all the text of all the files in one editor + information of lines and filles and such it would be compatible with dance I think.
Its just missing that you can apply the changes after you made them

**Comment by pomdtr** [comment]
You can use this extension to apply changes from the search editor : https://marketplace.visualstudio.com/items?itemName=jakearl.search-editor-apply-changes

**Comment by BeastyBlacksmith** [comment]
thanks @pomdtr, that will save me some headache today :)

**Comment by 71** [comment]
Ah yes, I rarely use the search editor so I didn't see what you were talking about. Closing this as the extension linked by @pomdtr does the job (and works alongside Dance).
