### ISSUE TITLE
downward directional selection stuck on blank line

### ISSUE THREAD

**Issue by jbytes1027** [71/dance#168]
When extending selected text with shift+j the cursor gets stuck on empty lines. Oddly this doesn't happen with shift+k or when the empty line is already selected.

https://user-images.githubusercontent.com/50090107/120668782-ca991f00-c45c-11eb-860f-cbed3a932c55.mp4

**Comment by losnappas** [comment]
In block-mode it's `shift+k` that gets stuck, caret mode `shift+j`

Example code block, keep the indent, do shift+j from first line down

```
	}
	messageFactory := messagefactory.New(dbClient, input)

	debugTimer := time.Now()
	messages := messagecontainer.NewMessages()
```

**Comment by 71** [comment]
That's probably the piece of logic I dislike the most about Dance. I hope my last commit settles this...
