### ISSUE TITLE
Issues I found in 0.5

### ISSUE THREAD

**Issue by losnappas** [71/dance#169]
Pretty sure some of these are block-mode only, also I'm not sure how many are me-only.

In no order:

1. Z only works every 2nd time
3. F2 (rename) is missing 1 character from the selection (block only)
5. Output-view has the "cursor off-screen" alarm, hides much of the view, probably could hide it in read-only views?
6. Shift+A takes you to next line (block-mode only)
7. Newlines have different color, same as Kakoune, but it seems to be the same as secondary selections, which is slightly confusing
8. Need docs on the stuff in "dance.modes"
9. Select word -> insert mode -> insert char -> selection is lost when typing in insert mode -> does not recover after going to normal
10. Bindings for (alt+shift+0) and (shift+0) + the `9` version are reversed
11. Existed prior to 0.5: going through selections does not go top to bottom
13. Spamming shift+e/shift+b moves other side of selection by a character (block only)
14. N is buggy, as is a-N

**Comment by 71** [comment]
Thanks for all the reports! I don't have time to go through them all, but I have a few remarks:

1. I'll look into it.
2. I'm not sure I can do much about this. The issue is that character-mode selections are actually always missing one character, which is added by Dance internally. Unfortunately, this means that non-Dance commands will interpret them differently. Your best bet is to re-assign `F2` to a command that extends the selections by 1, does whatever you want, and restores the selections. There's no really easy way to do this (except switching to `insert` mode and going back to `normal` mode afterwards), so I might add a command that automates this.
3. VS Code does not expose an API for read-only views, unfortunately. I also noticed this and believe some setting should be added for it, but I'm not sure how we could programmatically enable it.
4. Indeed. I'll look into it.
5. Not sure what you mean by this.
6. What do you suggest I add? Most of the "docs" are the details shown in the VS Code settings.
7. I'll look into it.
8. I'll look into it.
9. Going through? Some orders have been changed to be closer to Kakoune, maybe I made a mistake.
10. I'll look into it.
11. I'll look into it.

**Comment by losnappas** [comment]
For 11: Select a word with `N` (that's `shift+n`), then skip the next word with `n`, and the skipped word stays selected, but word that was supposed to stay selected moves to the next word.

For 9: When I do `shift-c` a couple of times, doing `shift-0` doesn't go from top to bottom, but goes bottom to top. For `alt-shift-c` it does go top to bottom, though.

For the docs: there's fields like "until", no clue how to use those, no hover info.

For 5: see pic. The top selection is the active one, newlines are in green, which is also the color of the secondary selection. It's a minor thing, though, will only be a problem once in a blue moon.
![image](https://user-images.githubusercontent.com/25119292/120980619-531e0500-c766-11eb-90cc-1a6ea3e0c494.png)

For the block mode stuff -- and this is a personal opinion ramble -- I was using it the way that I use the caret mode by default, but then when I have 0 characters selected and I press `d`, I then automatically select 1 and remove it, but if I do have characters selected I only remove those. It's a bit different from Kakoune, but works better in vscode, I think. It does mean that the block cursor style is out of the question, but I think that's just a minor inconvenience.

**Comment by losnappas** [comment]
Is this problem with `N` and `<a-N>` just me? I'm wondering where to start fixing it.

When I have 2 out of 5 selections with `N`, and I hit `n`, it moves the first selection instead of the last, which isn't supposed to happen.

Old version `N`+`n`


https://user-images.githubusercontent.com/25119292/132984763-f211c48e-7960-4edc-9bd1-3c889ff2035c.mp4

vs new version `N`+`n`


https://user-images.githubusercontent.com/25119292/132984768-11c5cbaa-838f-4119-8778-e74f7695a6f8.mp4



Also, do you think you could open the gh wiki (for public)?

**Comment by 71** [comment]
Ah, right. I haven't taken a look at the other issues because I've been busy, but I'll look into this one since I have a little bit of time.

Why are you asking about the wiki? I'd prefer having documentation directly in the repository, close to the code.

**Comment by 71** [comment]
https://github.com/71/dance/issues/169#issuecomment-917611807 fixed in 3a97a16c5e504d3465899cc470a5f833d8212c72.

**Comment by losnappas** [comment]
The wiki would be less about documentation, more about useful keybindings ppl might put into a centralized place.

Ex. take the `g` key, at start it's very useful to have the dropdown so you get to know the keys, but at some point you know them so you'd rather take the performance gain of using chorded keybinds like `g a`. That would be a nice to have in the wiki so everyone didn't have to craft them manually. I think it would be nice to have a low barrier of entry for sharing bindings .

**Comment by 71** [comment]
Great!

Is the wiki easier to contribute to? IMO we might as well have everything in the same place. For snippets there is the [`recipes`](https://github.com/71/dance/tree/master/recipes) directory.

**Comment by losnappas** [comment]
Yea, I think the wiki is the go-to. Personally, when I show up to a repo I check the top bar for a wiki and that's all. Going through the files is pretty cumbersome.

**Comment by 71** [comment]
Got it. I'll open up the wiki (though I won't add anything myself today).

**Comment by losnappas** [comment]
Clicking on the wiki redirects me to the repo front page. Did you make it public writable? I assume it redirects because it's empty.

**Comment by 71** [comment]
Can you try again? I might've configured it wrongly.

**Comment by losnappas** [comment]
Going to close this, they're either fixed or I've found a workaround for myself. I shoved too many issues in one to make sense anymore :stuck_out_tongue_closed_eyes:
