### ISSUE TITLE
[question] Is it possible to figure the length of the current selection in a keymap's "when" clause?

### ISSUE THREAD

**Issue by farcaller** [71/dance#170]
I'm trying to port over [this](https://discuss.kakoune.com/t/sublime-text-style-multiple-cursor-select-add-mapping/150) kakoune solution to VSCode, as it's more versatile than the VScode's own "Add next occurence". Is there any way I could bind both actions: 
expanding the selection and adding the next occurrence based on if the current selection is a single character or not?

**Comment by 71** [comment]
Right now, there is no way to get the length of the current selection in `when` clauses. I don't think it should be added, as AFAIK updating values in `when` clauses can be quite heavy, so doing it every time the selection changes would slow down VS Code. Additionally, it doesn't support multi-selections.

Your best bet is using the Dance API. Something like this.

```ts
const selections = Selections.current;

for (let i = 0; i < selections.length; i++) {
  const selection = selections[i],
        selectionText = text(selection);

  if (selectionText.length > 1) {
    const startPosition = moveTo(1 /* Direction.Forward */, selectionText, selection.end);

    if (startPosition !== undefined) {
      selections.unshift(Selections.fromLength(startPosition, selectionText.length));
      i++;
    }
  } else {
    const start = moveWhile.backward((c) => /\w/.test(c), selection.start),
          end = moveWhile.forward((c) => /\w/.test(c), selection.end);

    selections[i] = Selections.from(start, end);
  }
}

Selections.set(selections);
```
