### ISSUE TITLE
; key has unexpected behavior in caret mode

### ISSUE THREAD

**Issue by jbytes1027** [71/dance#172]
When pressing the ; key with an existing selection the selection is shrunk to one character like it should in block mode, but doesn't make sense in caret mode. Also when the caret is at the start of a selection it jumps forwards on char after shrinking, like it's in block mode.

**Comment by 71** [comment]
You're right. It makes sense when reducing to both edges since a common use for `a-S` is to select quotes or brackets, but a better default when reducing to the cursor with `;` is to allow empty selections.
