### ISSUE TITLE
Dance does not work on new untitled files with a selected language

### ISSUE THREAD

**Issue by pomdtr** [71/dance#186]
No dance cmd is available when using an untitled file after selecting a language.

Here is the error message: `error executing command "dance.modes.set.normal": given editor does not have an equivalent EditorState; has it gone out of view?`

**Comment by tshort** [comment]
Same here. I didn't realize it was Dance.

**Comment by 71** [comment]
Looks like selecting the language triggers a `OnDidCloseTextDocument` event followed by a `OnDidOpenTextDocument` event. There is no editor change, but Dance uses documents to keep track on which editor is where.
