### ISSUE TITLE
Add command to toggle extension

### ISSUE THREAD

**Issue by tomKPZ** [71/dance#189]
The vim extension has a vim.disableExtension setting and a toggleVim command [1].  If dance adds a similar setting, you'll be able to switch between kakoune and vim keybindings.  This would benefit users like myself who prefer the navigation commands of vim, but the editing commands of kakoune.

[1] https://marketplace.visualstudio.com/items?itemName=vscodevim.vim#vscodevim-settings

**Comment by 71** [comment]
This can be done by switching to a dummy Dance mode, i.e.

`settings.json`:
```json
"dance.modes": {
  "disabled": {},
},
```

`keybindings.json`:
```json
{
  "key": "...",
  "command": "dance.modes.set",
  "args": {
    "input": "disabled"
  },
  "when": "dance.mode != 'disabled'",
},
{
  "key": "...",
  "command": "dance.modes.set",
  "args": {
    "input": "normal"
  },
  "when": "dance.mode == 'disabled'",
},
```

**Comment by 71** [comment]
Note: a [recipe](https://github.com/71/dance/tree/master/recipes#enabling-or-disabling-dance) was added for this use case.
