### ISSUE TITLE
Spacemacs-esque leader key?

### ISSUE THREAD

**Issue by zetashift** [71/dance#196]
Hiya! I'm very new to Kakoune type keybindings, so I was wondering if, with Dance, it's still possible to define keybindings like Spacemacs, where `<space>` is a leader key to do all sorts of things. If so, how can I do this?

So basically for text editing I'd still use Dance, but in normal mode etc I am able to use `<space>` as a leader key.

**Comment by 71** [comment]
Hey there! Leader keys are implemented with the [`dance.openMenu`](https://github.com/71/dance/tree/master/src/commands#openMenu) command.

Here are two examples:
1. [Using a named menu](https://gist.github.com/nwwdles/d20c87e850917b8b68fc271f2841836d) (from https://github.com/71/dance/issues/112#issuecomment-657075932).
2. Using an inline menu (in `keybindings.json`), e.g.
    ```json
    {
      "key": "space",
      "command": "dance.openMenu",
      "args": {
        "menu": {
          "items": {
            ",": {
                "command": "editor.action.quickFix",
                "text": "quick fix",
            },
            ".": {
                "command": "editor.toggleFold",
                "text": "toggle fold",
            },
  
            "/": {
                "command": "editor.action.commentLine",
                "text": "toggle line comments",
            },
            "|": {
                "command": "editor.action.blockComment",
                "text": "toggle block comments",
            },
  
            "s": {
                "command": "workbench.action.gotoSymbol",
                "text": "go to file symbol...",
            },
            "S": {
                "command": "workbench.action.showAllSymbols",
                "text": "go to workspace symbol...",
            },
          },
        },
      },
      "when": "editorTextFocus && dance.mode == 'normal'",
    },
    ```

**Comment by zetashift** [comment]
Thank you very much!

**Comment by zetashift** [comment]
I've tried the named menu, but that isn't working, I copy pasted the following into the keybindings.json:
```
[
    {
        "key": "space",
        "command": "dance.openMenu",
        "args": { "menu": "leader" },
        "when": "!inputFocus || editorTextFocus && dance.mode == 'normal'"
    },
]
```
And the rest of the Gist is in the settings.json.

But I the error `"menu "" does not exist"`

**Comment by 71** [comment]
The API for named menus has changed. Now, `args` should be `{ "input": "leader" }`.

**Comment by zetashift** [comment]
You are too awesome (and quick!).

Thank you!

**Comment by zetashift** [comment]
I'm sorry bump this again, but how would I map 'A' to insert at the end of line? Currently [caps + a] does a simple insert, where [ shift + a ] does insert at the end of line. I'd like to have the same for [caps + a].

**Comment by 71** [comment]
Hmm, I'm not sure. My keyboard doesn't have a caps lock key, so I can't try anything anyway. The keybinding for "insert at line end" is [defined in `package.json`](https://github.com/71/dance/blob/187d4904beda30a55cc4a584eefda47b0d48082e/package.json#L2872-L2877), so you should probably try to make a similar keybinding and experiment with `capslock` (or remap capslock to something else in the OS).

**Comment by zetashift** [comment]
Ah that package.json had the answer, I ended up with this:

```
 {
    "key": "A",
    "when": "editorTextFocus && dance.mode == 'normal'",
    "title": "Insert at line end",
    "command": "dance.modes.insert.lineEnd"
  },
```
