### ISSUE TITLE
`searchselection` has no effect with `/`, `?`, `s`, etc..

### ISSUE THREAD

**Issue by Avi-D-coder** [71/dance#197]
Both variants of [`searchselection`](https://github.com/71/dance/tree/master/src/commands#searchselection), don't seem to do anything on [master](48bf08f92ef60c0fb794dd3a801a255f5cdf846b).

**Comment by 71** [comment]
The title of the command is admittedly not great, but it behaves like Kakoune: you use [`search.selection`](https://github.com/71/dance/tree/master/src/commands#searchselection) first to set the search register to the current selection, and then [`search.next`](https://github.com/71/dance/tree/master/src/commands#searchnext) (or one of its variants) to select the next match.

**Comment by Avi-D-coder** [comment]
Yeah, sorry I should have specified, the same key sequence in kak works.

**Comment by Avi-D-coder** [comment]
<kbd>*</kbd><kbd>/</kbd>should show `\bfoo\b` in search.
```
|foo| {
    bar
}

foo { 
    bar
}
```

**Comment by Avi-D-coder** [comment]
It work's without the <kdb>/</kdb> or regex search command.
The integration is what's missing.

**Comment by 71** [comment]
Ah, right, I see what you mean. Textboxes shown with `/` (and friends) should autofill with the current search? That's a good suggestion, yeah.
