### ISSUE TITLE
VS Code for the Web

### ISSUE THREAD

**Issue by tshort** [71/dance#198]
I tried adding Dance to Visual Studio Code for the Web (launched via GitHub). It's apparently not available in the browser. I'm curious if this might ever be possible.

**Comment by 71** [comment]
Ah, I thought I had done all the necessary steps, but I hadn't. I also didn't realize that VS Code web was available.

9a377a008041f876613fcda9151b320941315fc8 adds support for running as a web extension.

**Comment by 71** [comment]
Nvm. It works locally with `vscode-test-web --browserType=chromium --extensionDevelopmentPath=.`, but not on https://github.dev.

**Comment by tshort** [comment]
Cool stuff. It works. Amazing to have that available online.
