### ISSUE TITLE
Line/block comments

### ISSUE THREAD

**Issue by jtrakk** [71/dance#203]
Vscode has commands for comment/uncomment for line and block comments. How can I do these in Dance? 

I found https://github.com/mawww/kakoune/blob/master/rc/tools/comment.kak

**Comment by 71** [comment]
Those commands are built into VS Code. You can create a key binding to run them in Dance `normal` mode, e.g.

```json
{
  "key": "tab",
  "command": "editor.action.commentLine",
  "when": "editorTextFocus && dance.mode == 'normal'",
}
```

Use `editor.action.blockComment` to use block comments instead. VS Code will use its internal knowledge of the language of the current file to insert the comments (so you'll get `#` in Python, and `//` in C++).
