### ISSUE TITLE
Line numbers appear with find command

### ISSUE THREAD

**Issue by EdAyers** [71/dance#205]
Hi, I have turned off linenumbers with 

```
    "dance.modes": {
        "": {
            "lineNumbers": "off",
        },
        "insert": {
            "lineNumbers": "off",
        },
        "normal": {
            "lineNumbers": "off",
        }
    },
```

However the line numbers still pop in when I run a find command (eg by hitting `f` in normal mode).
Is there a way to turn off line numbers always?

Thanks

**Comment by 71** [comment]
Dance switches to `input` mode when using keybindings like `f` to show a state change to the user. Previously, Dance did not allow the `input` mode to be changed. With 5a57186926f887d90ae1699d9082c0bf321b5a04, you can also configure the `input` mode to disable line numbers:

```jsonc
"dance.modes": {
    "input": {
        "lineNumbers": "off",
    },
    // ...
},
```
