### ISSUE TITLE
'Insert after' inserts after the new line if it is at the end of the selection in 'character' selection behavior

### ISSUE THREAD

**Issue by Strackeror** [71/dance#216]
This may or may not be intentional, but I found this behavior surprising so I'll ask:
My current dance related settings are thus :
```json
    "dance.modes": {
        "normal": {
            "cursorStyle": "block",
            "selectionBehavior": "character",
            "lineNumbers": "inherit"
        }
    },
```
before pressing 'a'
![image](https://user-images.githubusercontent.com/13065324/143461618-a7e32407-0b2d-4bdb-86ad-b7137ed57f94.png)
after pressing 'a'
![image](https://user-images.githubusercontent.com/13065324/143461671-0ff71cdc-dc6b-46ff-9552-8783aae79a6a.png)

When a selection ends with a newline, meaning the empty space after the last character of a line is highlighted, using the 'insert after' command ('a') will start inserting after that newline. This is inconsistent with kak, and can be a bit annoying in contexts where full lines are selected.

**Comment by 71** [comment]
What version of Kakoune are you using? Both `v2020.09.01` and `v2021.11.08` behave this way.

**Comment by Strackeror** [comment]
the version that is on opensuse repositories, that is...  `2018.04.13 `
...ah

And it does work like dance on the debian repo's version. 
Welp, I'm clearly in the wrong here, sorry for the inconvenience.

**Comment by 71** [comment]
No problem, I also think this behavior is a bit counter-intuitive, but if you don't care about maintaining your selection you can get the same result with `A` (assuming that all your selections are already at the end of each line). I had a quick look at the [Dance code yesterday](https://github.com/71/dance/blob/f6fa71363dc4fb37a9bb5e4eb3dd9ea636becbf5/src/commands/modes.ts#L24) and don't think there's a possible trivial fix, but I could add an alternative command for `a` that does not go to the start of the next line.
