### ISSUE TITLE
Unfortunate interaction with jupyter notebooks

### ISSUE THREAD

**Issue by kazimuth** [71/dance#217]
Repro:
- Create a jupyter notebook
- Type some stuff in a cell
- Click in the middle of the cell
- Type "i"
- Type "esc"

This frequently (but not always?) kicks me out to a buffer containing only the contents of the cell, read-only. Not sure why.

Preferred behavior: go back to normal mode.

(This is bizarrely similar to a bug I ran into with Spacemacs evil keybindings and org-mode code cells. In that case the issue was that hitting "o" in a code cell would open a similar read-only buffer for the cell... Convergent evolution of bugs?)

**Comment by 71** [comment]
Looks like VS Code weirdly handles notebooks; https://github.com/microsoft/vscode/commit/10a3aefcd6cee02364337bc07f5353ee5d30df2c has a fix that also works for Dance.

**Comment by pomdtr** [comment]
Sadly the issue is still happening on my end :/

**Comment by 71** [comment]
Ah, right, I haven't updated the marketplace version of Dance in a while, my bad. `v0.5.9`, which contains the fix, should be live soon.
