### ISSUE TITLE
Feature Request: Menu to Display the Contents of Registers

### ISSUE THREAD

**Issue by Cody-Duncan** [71/dance#240]
Investigation of Issue #239 was made difficult by the fact that the contents of the registers aren't visible (insofar as I can tell). 
Ctrl + r was inserting the wrong text, but it was difficult to be certain whether this was errant behavior or user error without knowing the register's states.

#### Request: Implement a menu that displays a preview of the contents of the registers.

The plugin [kakoune-registers](https://github.com/Delapouite/kakoune-registers) looks like a good place to get inspiration for what that menu could look like.

**Comment by 71** [comment]
Fixed in db2fbbfb60b936e2f49ae71ae927e73abafe4cbd with a new Dance view:
![image](https://user-images.githubusercontent.com/7189784/156464650-5d46ec23-efab-4cb1-8390-072189a01b46.png)
