### ISSUE TITLE
Macros don't seem to work

### ISSUE THREAD

**Issue by tmewett** [71/dance#243]
Hi, firstly, thanks for this extension, and sorry if I'm misunderstanding this feature as I've never used Kakoune itself.

When I do something like `Qihello<esc>`, `Q` doesn't work to stop the macro (it is documented to start or stop a recording), and then when I do stop it by pressing the button in the status bar, pressing `q` to play it does nothing other than seemingly toggle insert mode on and off really fast. I tried only recording normal mode commands but that doesn't work either. It seems like it only records mode transitions?

Am I doing something wrong here?

**Comment by 71** [comment]
Hi,

Unfortunately macros need more work to work properly. They're technically implemented, but "break" (ie stop losing track of changes and aren't able to reproduce them later) fairly easily. Though for simple cases it should work, and `Qihello<esc>` is one such case. I can personally make it work with `Qihello<esc><pressing "stop recording">q`. Another issue here is that, indeed, the recording can't be turned off with `Q`.

**Comment by 71** [comment]
Bug for improving macros themselves: #244
