### ISSUE TITLE
Pipe commands using wsl

### ISSUE THREAD

**Issue by JJK96** [71/dance#248]
I'm using Dance on Windows. I want to use wsl as the shell for windows, so I can use unix commands.

I have set the following in my settings.json:
```
    "terminal.integrated.automationShell.windows": "wsl"
```

When I do `| # echo test`, I see the following output: 
![image](https://user-images.githubusercontent.com/11193274/161965358-0f2329dc-4cc8-4a1a-96ce-c54fb4eeb179.png)

When executing the command from powershell it works:

```
PS>wsl echo test
test
```

Has anyone managed to get this working with WSL?

**Comment by JJK96** [comment]
After a lot of debugging I found a working solution:

Install the extension only in WSL, not locally.

**Comment by 71** [comment]
Ideally we could run commands using WSL just by specifying it in the settings.

**Comment by farcaller** [comment]
@71 can you please elaborate on how `terminal.integrated.automationProfile` is supposed to be used? For me, `!#dir` works both in local vscode and in the wsl remote, producing the windows-side directory listing and `!#ls` doesn't output anything in either. I tried setting

```
"terminal.integrated.automationProfile.linux": {
    "path": "/run/current-system/sw/bin/bash"
  }
```

to no avail.

**Comment by 71** [comment]
@farcaller Unfortunately VS Code doesn't expose an API for running commands and getting their output, so "pipe" commands all run locally using the Node `child_process` API. It's possible to _start_ commands (by programmatically creating `shell` tasks and running them, or by creating terminals), but there is no API to grab their output.
