### ISSUE TITLE
Select register (") doesn't seem to work

### ISSUE THREAD

**Issue by tmewett** [71/dance#250]
Pressing `"` doesn't seem to do anything. Is it implemented? I see references to registers in the README etc. so it makes me think something isn't working. I'm on macOS and I don't have any custom keybinds for `"`

**Comment by 71** [comment]
Dance expects a key to be pressed after pressing `"`. It's much more subtle than Kakoune, but two things change when a key press is being expected (and the mode is changed to `input`): the cursor changes to a line (figure 1) and the status bar changes (figure 2). When a register is selected, the status bar changes again (figure 3).

Figure 1:
![image](https://user-images.githubusercontent.com/7189784/166104923-883c2215-3df5-449e-8b16-0bff3a863744.png)

Figure 2:
![image](https://user-images.githubusercontent.com/7189784/166104946-ceb31681-0280-4a34-8f65-7dce847f2aaf.png)

Figure 3 (after selecting the register `r`):
![image](https://user-images.githubusercontent.com/7189784/166104965-aecf380d-2694-45ef-9672-a7401e613e4c.png)

**Comment by tmewett** [comment]
That's what I mean, that doesn't work for me. However I just had a flash of inspiration and tried `@` (I use UK layout; it is the `"` key on Mac and US keyboards). That works as intended. So it looks like Dance may not be respecting keyboard layout with this command

**Comment by 71** [comment]
Unfortunately [VS Code doesn't allow key bindings where the key is `"`](https://github.com/71/dance/blob/74d2238150f9e0a91c4f54c9bd4c8248594184fd/package.json#L2798); in Dance, `"` is defined using [`Shift+'`](https://github.com/71/dance/blob/74d2238150f9e0a91c4f54c9bd4c8248594184fd/package.json#L2798) for compatibility with US keyboards.
