### ISSUE TITLE
`;` reduce selections to their cursor

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [71/dance#255]
Here is an example on what I expected, but it seems that the cursor in Dance will locate after the character but does not select the character.

https://delapouite.github.io/kakoune-tv/#58860440c57fb30006000004

**Comment by 71** [comment]
This is intended in `caret` selection mode. However since it's fairly common to want to select the character at the end of the selection, you can remap `;` this way to get the behavior you desire:

```jsonc
{
  {
    "key": ";",
    "command": "dance.selections.reduce",
    "args": {
      "empty": false,
    },
  },
  // ...
}
```

**Comment by sschneider-ihre-pvs** [comment]
Is there an option for this? Or should there be?

**Comment by 71** [comment]
Since there are already two ways to get that behavior (either by enabling `character` mode or by remapping `;`), I don't think an option is necessary.

**Comment by sschneider-ihre-pvs** [comment]
Where is the `character` mode?

**Comment by sschneider-ihre-pvs** [comment]
found it
"selectionBehavior": "character",

**Comment by sschneider-ihre-pvs** [comment]
ok that is not it
