### ISSUE TITLE
Dance.run fails on "vanilla" commands

### ISSUE THREAD

**Issue by losnappas** [71/dance#262]
Since 0.5.10, with a keybind like

```
  {
    "key": "ctrl+a",
    "command": "dance.run",
    "args": {
      "commands": ["cursorHome"]
    }
  },
```
it fails with
```
error executing command "dance.run": Cannot read properties of undefined (reading 'map')
```

**Comment by bfulop** [comment]
Thanks @71 for the quick resolution. I wanted to raise this issue too. 

I tested the latest version `0.5.11` and now the [go to settings from the wiki](https://github.com/71/dance/wiki/%60goto%60-Without-the-Menu-(Faster%3F)) are working again! 🎉
