### ISSUE TITLE
Maintain selection when switching modes

### ISSUE THREAD

**Issue by adekbadek** [71/dance#271]
When switching mode from normal to insert, the current selection is lost. Example: 

1. in normal mode, select a word
1. switch to insert mode 
1. input some characters

the characters will be inserted before the word. The selection should be maintained (perhaps that's an option?) and in step 3 above the characters should replace the word, which was selected.

**Comment by yyogo** [comment]
Does not replicate for me - the selection stays when you insert and go back to normal mode (unless you modify the selection, but this behavior is consistent with Kakoune). 

>the characters should replace the word, which was selected.

If you want to replace the selection you can use `c`

**Comment by adekbadek** [comment]
> the selection stays when you insert and go back to normal mode 

It's about the other way around – from normal to insert.

**Comment by adekbadek** [comment]
Brilliant, thank you! Exactly what I was looking for.
