### ISSUE TITLE
Repeating last insert mode change with `.` modifies at last insertion point instead of selection

### ISSUE THREAD

**Issue by timjs** [71/dance#28]
To reproduce:

0. Open a new file and insert `1 2`.
1. Select `2` by hitting `b`, hit `c` and change it to `3`.
2. Select the `1 ` by hitting `bb`, hit `.`.

Expected output:
* `3 3`: `1` is changed to `3` as well (repeat last edit action)

Actual output:
* `1 33`: the edit is repeated at the last insert position

**Comment by 71** [comment]
Everything related to history and repeats has _some_ foundation, but isn't considered as working right now. It's definitely in my todo list but will require more work than I can put right now. If you'd like to try to fix it yourself, you're welcome to try!

**Comment by 71** [comment]
I managed to fix this one problem "easily," but I have no doubt many other problems regarding repeats / history will remain.

**Comment by timjs** [comment]
Maybe I'll have some more spare time in december. Thanks for trying anyway!
