### ISSUE TITLE
Sneak, easymotion, or vscode jumpy (jumpy2)

### ISSUE THREAD

**Issue by merlindru** [71/dance#284]
First off, dance is awesome! Thanks for making & maintaining it 😄 

I'd like to use something like [Jumpy2](https://marketplace.visualstudio.com/items?itemName=DavidLGoldberg.jumpy2) with Dance. However, while invoking it with my set keybind (shift+enter) works really well, when I enter the displayed characters, Dance takes over.

Is there any way I could make these work together?

Thanks!!

**Comment by 71** [comment]
Thanks!

Dance key bindings are all conditionally activated based on the current mode ([example](https://github.com/71/dance/blob/7d73bfc0245a8ce447323bb456fa3e8f8f977eda/package.json#L2519)). To enter some other command, you should switch to another mode, enter your command, and go back to the previous mode. In Dance, the standard mode for this is the `input` mode, which also transforms your cursor from a vertical line to an horizontal line while waiting for input (e.g. after pressing `t` or `f`). [Jumpy2 also uses these context keys](https://github.com/DavidLGoldberg/jumpy2/blob/648fbbd50de38b7faa369b0f01c7f5f3dd3e84f1/package.json#L133), so you could override Dance keybindings to only work if `jumpy2.jump-mode` is false.
