### ISSUE TITLE
Shell pipe not executed in workspace

### ISSUE THREAD

**Issue by PJungkamp** [71/dance#286]
kakoune lets me insert the local directory/file names/contents using `ls` or `cat`.

I'd expect `!# ls` to insert a list of all file in the working directory. Instead it inserts my home directories contents.
Checking with `!# env` shows that the command runs in an empty environment (not even `PATH` is present!). See
```
PWD=/home/redacted
SHLVL=0
_=/usr/bin/env
```

This is the same with `terminal.integrated.automationProfile.linux` unconfigured and with a basic configuration
```json
"terminal.integrated.automationProfile.linux": {
    "path": "/bin/sh",
    "args": ["-c"]
}
```

I'm unable to inject the `${workspaceFolder}" into the environment of the shell pipes.

**Comment by 71** [comment]
Thanks for the report! b144b02b5a8baa4d14e3a8511d7ab9f0e0b0ade0 should fix it, but I only tried it on Windows so I would welcome a confirmation!

**Comment by PJungkamp** [comment]
I'd like to try it!

Are there build instructions?
I'm inexperienced with npm.

I installed `vsce`, `yarn` and `ts-node` and tried to build using:
```shell
npm install
npm run package
```

Which complains about a missing `process` dependency.

**Comment by 71** [comment]
Uuuh I'm not quite sure this works. In my case I run `yarn` at the root of the repository (which installs dependencies), then I open the repo in VS Code, and in the "Run" view of VS Codes I pick "Launch extension" (or something like that). With this approach you can set breakpoints and debug Dance while using it, which is nice.

**Comment by PJungkamp** [comment]
My bad. With `yarn` it's working. Seems like `npm` was the problem. I had seen the `package.json` and just assumed `npm`.

The shell commands work great! E.g. generating a filesystem link using `ls`/`fzf`/`realpath`.

**Comment by 71** [comment]
Ah, glad to know it works! Yeah `package.json` is used by both `npm` and `yarn`, but the file that gives yarn away is `yarn.lock` :)
