### ISSUE TITLE
Extend goto keys

### ISSUE THREAD

**Issue by timjs** [71/dance#29]
Is there an easy way to add new key bindings under the goto subspace? Adding something like this:
```
{
    "key": "g n",
    "command": "editor.action.marker.next",
    "when": "editorTextFocus && dance.mode == 'normal'"
},
```
will render all existing goto bindings useless.

**Comment by 71** [comment]
If I understand correctly, you'd like to add new entries to the `goto` menu? Right now it's not possible, but I can see how it would be implemented:
- Make all `goto` subcommands public and accessible with no default keybinding.
- Add a new preference `dance.gotoCommands` that would look like
  ```json
  { "h": "dance.goto.lineStart",
    "l": "dance.goto.lineEnd",
    "i": "...",
  }
  ```

Then you'd be able to override the default with the existing keybindings plus
```json
"n": "editor.action.marker.next",
```

**Comment by timjs** [comment]
Yes, that would be the way to go I think!

**Comment by timjs** [comment]
Should not be high on the priority list, one can still bind these kind of actions to a leader key.

**Comment by 71** [comment]
I'll try to keep this on my mind, but I can't work on it right away. Thanks for your patience!

**Comment by yuchenshi** [comment]
Shall we merge this into #86 (or the opposite)? I somehow did not find this issue and created #86 as a duplicate, sorry about that. But either way I think https://github.com/71/dance/issues/86#issuecomment-610006062 is a great way to tackle this (and also #40) and feel free to put a `help wanted` tag if needed. (I'm looking forward to contributing more to Dance when I have some spare time.)

**Comment by 71** [comment]
@yuchenshi You're right. I forgot about this issue too, and #86 is more general. I'm closing this one, and we can continue the conversation there.

#86 should be reasonably easy to implement, but it's currently blocked by the upcoming refactor.
