### ISSUE TITLE
Normal mode in integrated terminal

### ISSUE THREAD

**Issue by losnappas** [71/dance#298]
I'd assume there is way of making modes work in the integrated terminal. Currently Dance gives error `active editor required` when clicking on the modes button while focusing terminal.

Is there an API limitation, or could this be done?

**Comment by 71** [comment]
I doubt this is possible as terminals typically handle all keybindings themselves (as a good example, typically even different shells will support different keybindings, e.g. [`vi` mode in Nu](https://www.nushell.sh/book/line_editor.html)).

Personally, I use Nu with `$EDITOR = hx`, so `ctrl-o` opens up the current shell command in Helix where I can perform more advanced edit operations before switching back to Nu.

**Comment by losnappas** [comment]
For anyone ending up here: there's a new~ish command in vscode that opens a text buffer of the terminal content: `workbench.action.terminal.focusAccessibleBuffer`. I think you need an accessibility setting toggled on, I forget which one.

Downside is that it doesn't have any syntax hl, so it's a bit tedious to navigate. What I was hoping in this issue was that I could enable normal mode to copy text/move around, not necessarily to edit it, but yeah the accessible buffer will get there at some point.

**Comment by losnappas** [comment]
To anyone dropping in, I found this, very close to what I want but needs work: https://github.com/jeffgran/vscode-comint
