### ISSUE TITLE
Question: adding new modes and keybindings

### ISSUE THREAD

**Issue by jonaprieto** [71/dance#302]
I couldn't find clear explanations of how to:

- Add a new mode (as a template, known options I can setup)
- Add new keybindings in different modes (as a template)
- How to create a keybinding that calls different commands

**Comment by 71** [comment]
- Adding a new mode is done by [adding a new entry to the `dance.modes` configuration](https://github.com/71/dance#custom-modes).
- Keybindings are defined in VS Code and use the `when` clause to only trigger in the correct mode. For instance:
  ```jsonc
  {
    "key": "v",
    "command": "dance.modes.set",
    "args": { "input": "extend-select" },
    "when": "editorTextFocus && dance.mode == 'normal'"
  },
  ```
- Multiple commands can be run using `dance.run`, for instance in the last example of the [command documentation](https://github.com/71/dance/tree/master/src/commands#run).

**Comment by jonaprieto** [comment]
You could probably add this to the README too.

**Comment by 71** [comment]
Thanks for the suggestion. I added a link to https://github.com/71/dance/wiki/Extend-select-mode to the README in 1faf63fa1f056282c0043045dc92646a9905c869.
