### ISSUE TITLE
Input vs Insert mode

### ISSUE THREAD

**Issue by jonaprieto** [71/dance#303]
What exactly is the difference between these two modes?

Sometimes I can see "input" in the status bar and sometimes it says "insert".

**Comment by 71** [comment]
The `insert` mode is the regular mode for editing text, where keys are directly written to the editor, like in Kakoune and Vim. The `input` mode is the mode that is temporarily switched to when a command expects an input, such as `t` or `g`.

**Comment by jonaprieto** [comment]
That solves the mystery. Thanks!
