### ISSUE TITLE
Selections are forgotten when entering insert mode

### ISSUE THREAD

**Issue by timjs** [71/dance#31]
Kakoune keeps track of selections when entering insert mode, Dance doesn't. To reproduce:

1. Select a word `hello`
2. Hit `i` to enter insert mode
3. Do some edits
4. Hit escape to exit insert mode

Expected output:
* Old selection is restored.

Actual output:
* There is no selection any more.

(When hitting `a` instead of `i`, the selection gets extended with the entered text.)

I'm not entirely sure if implementing this matches the philosophy that "Dance's only goal is to provide VS Code-native commands and key bindings that are inspired by Kakoune" or not. My use case was adding quotes around every selection. Maybe there is a better way to do this.

**Comment by geier1993** [comment]
Hey timjs, 
I've implemented this feature in an open pull request: https://github.com/71/dance/pull/35
Yet nothing has been reviewed. Would you mind testing the branch?

Clone my branch,
Run `yarn install` and then `vsce package` to create a package.
Finally install it with `code --install-extension dance-0.1.7.vsix`

**Comment by timjs** [comment]
Hey @geier1993! Sorry, don't have much time to do further testing these days. Maybe after Christmas!

**Comment by yuchenshi** [comment]
This is now fixed on master. PTAL.

**Comment by timjs** [comment]
Will do!

**Comment by 71** [comment]
Note: the approach used for this is very conservative, and could be improved. Right now, I've noticed that the saved selection will be dropped in cases where it wouldn't be dropped in Kakoune.

The logic is in [`src/state/editor.ts`](https://github.com/71/dance/blob/2b67f6a233d3a9e933f3266e4f6b17ce5f5fbff8/src/state/editor.ts#L268), so if you find improvements to the heuristics please let me know!
