### ISSUE TITLE
Update to Kakoune 2023.08.05

### ISSUE THREAD

**Issue by rosingrind** [71/dance#311]
I've mentioned latest release even though it's a bug fix. In current state, dance misses some big changes, some of them:
- `SPC` and `,` are swapped
- `x` line selection behavior was changed
- `undo` for selections

**Comment by rosingrind** [comment]
Taking this opportunity to ask an additional question: in `kakoune` you use `(` and `)` to rotate main selection, and `a-(` or  `a-)` to rotate selection content. You can select things, drop some of selections, and cycle them. How do I do this in `dance`? `(` and `)` performs straight "rotate selection content" operation, is this an outdated mechanics or it always was like that in `dance` by design?

**Comment by ilyagr** [comment]
A lot of these changes (possibly all of them) are available in the prerelease version of Dance. Just click on the appropriate button in VS Code over the Dance extension in the Extensions view.

The "normal" version in the extension marketplace is quite outdated by now, and has known bugs.

**Comment by 71** [comment]
Seems like it's fairly common for users to use the prerelease version, I should probably upgrade the released version. AFAIK I can't get download stats in the store so I'll have to trust it will be fine. Sorry for gating recent features in prerelease version so long!
