### ISSUE TITLE
Can't turn off current-line highlighting(?)

### ISSUE THREAD

**Issue by victorz** [71/dance#324]
Hello!

I love this extension. Have to say that first of all. Thank you for making it!

I have run into something that bothers me a bit though. The current line is highlighted, seemingly by this extension, and I haven't been able to figure out a way to disable it.

When I'm in normal mode, the current line is highlighted, but in insert mode it is not. My `editor.renderLineHighlight` setting is set to `"gutter"`, which should make it not highlight the current line -- only the gutter on the current line. I've also tried every other valid value for that setting, including `"none"`, to no avail.

It looks like this:

https://github.com/71/dance/assets/7494/878aae85-1197-4992-a6d5-a4d1590b7878

Is this expected behavior in Dance? Is it actually caused by Dance? If so I'd love to disable it, so if it's not currently possible, could I request an option to be able to turn this off?

Thanks so much!

Running Dance v0.5.14, but also tried pre-release version v0.5.14002.

**Comment by 71** [comment]
Indeed this is done on purpose to make it more obvious where the main selection is. This can be disabled with the following configuration:

```jsonc
    "dance.modes": {
        "normal": {
            "decorations": {
                "isWholeLine": false,
            },
        },
    },
```

You can also play with `decorations` to find something that better suits you, like a darker color for the `backgroundColor`.
