### ISSUE TITLE
What happened to the X and Shift+X commands?

### ISSUE THREAD

**Issue by Dilettante44** [71/dance#326]
Suddenly, these are bound to Dance: Ignore for my normal mode though I don't recall having made such changes to the command. I noted that I had an update to the extension just last week. I really love this extension, but I found this change to be jarring because I didn't expect it. Also really glad to see that this extension still lives! 😄

**Comment by Delapouite** [comment]
Hi. You'll find information about this in the following thread : https://github.com/71/dance/issues/319

**Comment by Dilettante44** [comment]
Thank you very much for the response, I appreciate it
