### ISSUE TITLE
Option to not justify current line number with relative line numbers

### ISSUE THREAD

**Issue by wmstack** [71/dance#328]
Not a fan of having the current line number justified to the left
<img width="68" alt="image" src="https://github.com/71/dance/assets/58462210/d889c07f-d109-40e7-8cb2-bf64ffe0a2b5">

Compare with Zed editor, which also has relative line numbers in normal mode
<img width="68" alt="image" src="https://github.com/71/dance/assets/58462210/b6ffc8cb-f781-4cab-b7d6-adc4dc313eea">

The different colour of the line number is enough to distinguish it for me, so I hope there is an option to disable the way the current line number is justified.

**Comment by 71** [comment]
Hey there!

Dance doesn't change anything there, AFAIK this is strictly managed by VS Code. I don't even know if VS Code exposes the ability to change this.

**Comment by ktnyt** [comment]
> Dance doesn't change anything there, AFAIK this is strictly managed by VS Code. I don't think VS Code exposes the ability to change this.

I find this response a bit misleading as the README clearly states that Dance does in fact alter the setting value in normal mode. Maybe a short explanation of how to override this behavior will be helpful to some but this is just my two cents.
https://github.com/71/dance/blob/7bf14636eac5422dd22af9964c2555ee8d3e4ef6/README.md?plain=1#L180-L181

@wmstack Here's how I managed to switch to using absolute line numbers in normal mode just in case you were still wondering.

```json
{
  // other vscode settings
  "dance.modes":{
    "": {
      "hiddenSelectionsIndicatorsDecoration": {
        "after": {
          "color": "$list.warningForeground"
        },
        "backgroundColor": "$inputValidation.warningBackground",
        "borderColor": "$inputValidation.warningBorder",
        "borderStyle": "solid",
        "borderWidth": "1px",
        "isWholeLine": true
      }
    },
    "input": {
      "cursorStyle": "line-thin"
    },
    "insert": {
      "onLeaveMode": [
        [
          ".selections.save",
          {
            "register": " insert"
          }
        ]
      ]
    },
    "select": {},
    "normal": {
      "lineNumbers": "inherit",
      "cursorStyle": "block",
      "decorations": {
        "applyTo": "main",
        "backgroundColor": "$editor.hoverHighlightBackground",
        "isWholeLine": true
      },
      "onEnterMode": [
        [
          ".selections.restore",
          {
            "register": " ^",
            "try": true
          }
        ]
      ],
      "onLeaveMode": [
        [
          ".selections.save",
          {
            "register": " ^",
            "style": {
              "borderColor": "$editor.selectionBackground",
              "borderStyle": "solid",
              "borderWidth": "2px",
              "borderRadius": "1px"
            },
            "until": [
              [
                "mode-did-change",
                {
                  "include": "normal"
                }
              ],
              [
                "selections-did-change"
              ]
            ]
          }
        ]
      ]
    }
  }
}
```
