### ISSUE TITLE
up/down doesn't work in command palette?

### ISSUE THREAD

**Issue by max-sixty** [71/dance#336]
I'm checking out Dance again as an alternative to the vim extension since https://github.com/71/dance/issues/18 seems to be partly fixed.

Currently up / down doesn't work in the command palette — I hit Cmd+Shift+P, and then `down` doesn't navigate down. 

When I add this exclusion to the keybindings config:

```
{
        "key": "down",
        "command": "-dance.changeInput",
        "when": "inputFocus && !textInputFocus"
    }
```

...then it works fine, and I get the movement I'd expect:

```
[KeybindingService]: \ From 27 keybinding entries, matched quickInput.next, when: inQuickInput && quickInputType == 'quickPick', source: built-in.
```

I'm guessing there's something I'm doing wrong given the severity of this, but any idea what might be happening? I tried on a blank profile with only this extension and still get this behavior.

**Comment by ilyagr** [comment]
I think I managed to reproduce it. I could *not* reproduce this at all with VS Code 1.89.

With VS Code 1.90, I can reproduce it with the *release* version of the extension, but not the *pre-release*.

@max-sixty, are you on 1.90? Do you still have the problem if you upgrade to the pre-release version?

**Comment by max-sixty** [comment]
It works fine on the pre-release! I'll close...

**Comment by 71** [comment]
Argh, sorry, I encountered this in the 1.90 prerelease, released a fix in a Dance pre-release, but forgot about it in the meantime and never released a proper version.
