### ISSUE TITLE
Implement view commands

### ISSUE THREAD

**Issue by sinhpham** [71/dance#40]
Kakoune has view commands to help navigating: https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#view-commands

Would love to see those commands implemented in Dance.

**Comment by yuchenshi** [comment]
I'm curious how much of it can be implemented with the `dance.menu` setting in 0.3.0 and native VSCode scroll commands.

Also for `V` (view lock) we may introduce a `dance.showMenu.locked` command.

**Comment by pomdtr** [comment]
I did try it without success : 

```json
        "view": {
            "items": {
                "vc": {
                    "text": "center cursor",
                    "command": "revealLine",
                    "args": [
                        "__line",
                        "center"
                    ]
                },
                "t": {
                    "text": "cursor on top",
                    "command": "revealLine",
                    "args": [
                        "__line",
                        "top"
                    ]
                },
                "b": {
                    "text": "cursor on bottom",
                    "command": "revealLine",
                    "args": [
                        "__line",
                        "bottom"
                    ]
                },
                "j": {
                    "text": "scroll down",
                    "command": "editorScroll",
                    "args": [
                        "up",
                        "line",
                        1,
                        true
                    ]
                },
                "k": {
                    "text": "scroll up",
                    "command": "editorScroll",
                    "args": [
                        "up",
                        "line",
                        1,
                        true
                    ]
                }
            }
```

We need to be able to access the line number dynamically (`__line` param). I quite like the implementation in this extension : https://marketplace.visualstudio.com/items?itemName=johtela.vscode-modaledit.

But even when the params are fixed, i'm not able to successfully use the command :-/

**Comment by 71** [comment]
I don't know about "revealLine", but the arguments for "editorScroll" should be `[{ to: ..., by: ..., value: ..., revealCursor: ... }]` (unless there are two ways to send arguments, but I'm not aware of that).

Adding dynamic values is a good idea, but I'd prefer a syntax like $line, which is closer to what VS Code does with launch and build tasks.

**Comment by pomdtr** [comment]
Sadly there is no var api in vscode :-/ : https://github.com/microsoft/vscode/issues/2809

**Comment by pomdtr** [comment]
Would you be willing to add three more commands in dance wrapping the `revealLine` command ?

**Comment by tshort** [comment]
I may be missing something. Even if "view" is added to `dance.menu`, how do you assign that to the "v" key?

**Comment by pomdtr** [comment]
In your keybinding.json file

```
    {
        "key": "v",
        "command": "dance.openMenu",
        "args": {
            "menu": "view"
        },
        "when": "editorTextFocus && dance.mode == 'normal'"
    },
```

**Comment by 71** [comment]
@pomdtr Yep, unfortunately. For now, I'm only talking about an obvious replacement like

```js
if (arg === '${dance:mainSelectionActiveLine}')
  arg = getMainSelectionActiveLineNumber()
```

**Comment by 71** [comment]
[View commands were added in Dance 0.5](https://github.com/71/dance/commit/2d38438e15724f13cb2896f39b56edbaa6eb97ac#diff-1b416a402f08061d0f32d538b3fd2c71dd00f657e136e75b3ab16dcf9549ed08).

Note that VS Code does not expose an API for scrolling horizontally, so those were omitted from the view menu.
