### ISSUE TITLE
9w selects 9 words rather than the 9th word

### ISSUE THREAD

**Issue by yuchenshi** [71/dance#50]
In kakoune, `9w` (lower case `w`) moves forward by 9 words, selecting the 9th word. However, in dance it will select from current active to 9 words later, for a total selection of 9 words (as if `9W` with Shift+W were used).

Is this something worth fixing? I can draft a PR for this.

**Comment by 71** [comment]
Thanks for the report! Looks like an oversight from me.

Absolutely, in those cases we try to match Kakoune's behavior. If you want to take care of it, take a look at `registerTo{Next,Previous}Word` in `src/commands/move.ts`.
