### ISSUE TITLE
Add git tags to the version bump commits

### ISSUE THREAD

**Issue by waldyrious** [71/dance#52]
It would be nice to have easy access to the list of versions. The releases don't have to be published on GitHub, but just creating the tags would already populate the listing at https://github.com/71/dance/releases ([example](https://github.com/git/git/releases)).

For convenience, here's the list of releases so far:

- v0.1.0 → b20d03aef5e53c04bb1a8546af1cafec7770c3ed
- v0.1.1 → 4211d71203e1904dd88463b5ed7be30be484a90c
- v0.1.2 → 7e4c15373b054880b65e895a178454dc38b0e454
- v0.1.3 → ac2dc14d37cdcb01fa6b101a8f0cbf3276601a20
- v0.1.4 → f89033576034e2cb817616a12444eb8e8ccd5701
- v0.1.5 → 3f955426ea72b51c9550bab6528e3ab252de660d
- v0.1.6 → 853237f4b84ad2b55859057ffb1f40e01152c876
- v0.1.7 → 120cfcb7727226722da9eb8c32a959f4d0699017
- v0.1.8 → 71fa19fe73dc07273cc5cab28c1eec1e4081a367
- v0.1.9 → bd27b101f1f3b977fb19400f2dc8527959ae1fa8

(If you're feeling generous, a CHANGELOG.md file would be nice as well!)

**Comment by nightscape** [comment]
Github actions that automatically publish new builds might also be helpful, especially once more people start contributing and releases should be able to publish.
Here's a Github action which would be able to do this:
https://github.com/lannonbr/vsce-action
If there's interest, I could try to help here.

**Comment by 71** [comment]
@waldyrious Good suggestion! Thank you for making the list as well, it helped.

Funnily enough, I thought about making a changelog earlier today, but I feel like it would lead me to procrastinate releasing new versions, so I'd like to wait until Dance gets a little more stable before doing it. Although incomplete and inconvenient, for now interested users can just look at the commit history.

@nightscape Good idea as well. I feel a little bad knowing an entire Docker instance will be spawned and all the required dependencies will be fetched every time I release a version though, and I like the manual labor.

If other people eventually get the right to publish releases without my approval, then I'll consider this again.
