### ISSUE TITLE
One-character selections are treated as directional

### ISSUE THREAD

**Issue by 71** [71/dance#53]
Unlike Kakoune, one-character selections are treated as directional rather than non-directional. In practice, this means that changing the cursor position with a one-character selection may not work correctly in some cases (see https://github.com/71/dance/pull/48#discussion_r382224751 for context).

**Comment by yuchenshi** [comment]
Now that I look a closer look at it, it's not just extending, but also moving / selecting as well in some cases:

Given this (selecting `d` as a single character)
```
abc [d]ef
```

Press `e` in Dance gives you `abc d[ef]`. However in Kakoune, it is `abc [def]` instead.

**Comment by 71** [comment]
@yuchenshi Damn, I specifically took this case into account in my last changes, but must have somehow changed the behavior at some point. Thanks for the report!

**Comment by yuchenshi** [comment]
Yeah, I think your latest changes fixed it for `E` but not `e` somehow.

**Comment by bm-stschneider** [comment]
so, is a one character selection possible? if i have the cursor under a character and hit r it will be not replaced for example.

**Comment by yuchenshi** [comment]
@bm-stschneider This is possible if you disable "allow empty selections" in the extensions config. The issue here tracks some of the corner cases.

**Comment by bm-stschneider** [comment]
Great, I will have a look.

**Comment by yuchenshi** [comment]
This should be mostly fixed on `master`. Please make sure to set cursor mode to `character` if you want one-character selections and non-directional behaviors. Please open a new issue if you find a new case.
