### ISSUE TITLE
Cursor style not set on startup

### ISSUE THREAD

**Issue by timjs** [71/dance#54]
0.2.0 is awesome! Thanks for all the work on single char selections and the customisation options added. There are a few small bugs however. I'll fill in separate issues.

The _Normal Mode: Cursor Style_ option is not respected when starting VSCode. I.e. the default cursor is rendered instead. After entering insert mode and normal mode again, it works correct.

**Comment by 71** [comment]
Thanks for the feedback! I'll try to take care of things ASAP.
