### ISSUE TITLE
Inconsistent behaviour of `<a-p>` and `<i-p>` on last paragraph of file

### ISSUE THREAD

**Issue by timjs** [71/dance#57]
Using `<a-p>` and `<i-p>` on the last paragraph of a file doesn't select the whole paragraph, it only selected upwards, till the last newline. Only happens when the last line of the file is not an empty line!

**Comment by yuchenshi** [comment]
I've added a few tests cases to track Kak's behavior on master and fixed Dance accordingly. Let me know if you still find differences.
