### ISSUE TITLE
`<i-(>` and `<a-(>` and friends should select a group when cursor is on boundary

### ISSUE THREAD

**Issue by timjs** [71/dance#58]
### Opening paren

`<i-(>` and `<a-(>` work fine when the single char selection is inside a group, but they don't make the right selection when the single char selection is the opening paren.

To reproduce:
1. Place single char selection on a opening paren
2. Hit `<i-(>` (or `<a-(>`)

Expected output:
* Text inside parens should be selected (including parens itself)

Actual output:
* No change of selection

### Closing paren

Additionally, when the single char selection is on the closing paren, `<a-(>` works fine, but `<i-(>` selects everything inside the parens _including the closing paren_. This should not be the case.

To reproduce:
1. Place single char selection on a closing paren
2. Hit `<i-(>`

Expected output:
* Text inside parens should be selected

Actual output:
* Text inside parens is selected _including closing paren_

###  Other delimiters

The same bugs happen for other delimiters like `[]`, `{}`, and `<>`.

**Comment by yuchenshi** [comment]
I've got tests and a fix on the `unstable` branch in 1c18e0de9df10ec5cba82195f9986e6ff8744758 , but I have little idea whether my rewrite breaks caret-based selections yet. We'll do more tests and may merge `unstable` to master once all objects are working and things are more stable.

**Comment by yuchenshi** [comment]
Closing since it's now merged to master. We'd appreciate any help testing both caret and character mode. Especially caret mode.
