### ISSUE TITLE
`W` and `E` do not include current single char selection

### ISSUE THREAD

**Issue by timjs** [71/dance#62]
To reproduce:
1. Place single char selection on some word character.
2. Hit `W` (or `E`)

Expected behaviour:
* Selection, including current single char, gets extended to next word (end of word)

Actual behaviour:
* Selection gets extended to next word (end of word), _without_ current single char

**Comment by Delapouite** [comment]
Related discussion on Kakoune's side https://github.com/mawww/kakoune/issues/3132

**Comment by timjs** [comment]
Thanks @Delapouite, that is indeed an interesting discussion and not easily solved.

What I tried to describe above, is actually a bug. It's about the difference between using `e` and `E`.

Currently in Kakoune:
```
[a]bcd    -e->    [abcd]
[a]bcd    -E->    [abcd]
```

Currently in Dance (with single selection chars):
```
[a]bcd    -e->    [abcd]
[a]bcd    -E->    a[bcd]
```
