### ISSUE TITLE
Map ':' to workbench.action.showCommands

### ISSUE THREAD

**Issue by Delapouite** [71/dance#66]
Hello

The Command Palette in VSCode shares a similar purpose with the command/prompt mode of Kakoune.
Therefore, as `ctrl+shift+p` is quite cumbersome to type for an action that is so frequent, I reckon pressing `:` while in normal mode should also triggers the `workbench.action.showCommands` action.

**Comment by 71** [comment]
Technically this can be achieved without dance by adding a user keybinding, but I do think it's a nice default. Thanks for the suggestion.

**Comment by 71** [comment]
Looks like VS Code ignores keybindings contributed by extensions if those keybindings are for commands defined outside of the extension, so adding that default keybinding doesn't work. A simple workaround would be to have our own wrapper function, but I'm not sure that's better than just having custom keybindings.
