### ISSUE TITLE
Feature Request: Saving/Restoring Selections

### ISSUE THREAD

**Issue by geier1993** [71/dance#7]
How can I access the position of the last change?

In vscodevim it is implemented like:

```
// src/actions/commands/actions.ts
@RegisterAction
class CommandGoLastChange extends BaseCommand {
  modes = [ModeName.Normal];
  keys = [['`', '.'], ["'", '.']];
  isJump = true;

  public async exec(position: Position, vimState: VimState): Promise<VimState> {
    const lastPos = vimState.historyTracker.getLastHistoryStartPosition();

    if (lastPos !== undefined) {
      vimState.cursorStopPosition = lastPos[0];
    }

    return vimState;
  }
}
```

and 

```
// src/history/historyTracker.ts

  /**
   * Gets the ending cursor position of the last Change of the last Step.
   *
   * In practice, this sets the cursor position to the end of
   * the most recent text change.
   */
  getLastChangeEndPosition(): Position | undefined {
    if (this.currentHistoryStepIndex === 0) {
      return undefined;
    }
    const lastChangeIndex = this.historySteps[this.currentHistoryStepIndex].changes.length;
    if (lastChangeIndex === 0) {
      return undefined;
    }
    return this.historySteps[this.currentHistoryStepIndex].changes[lastChangeIndex - 1].end();
  }

  getLastHistoryStartPosition(): Position[] | undefined {
    if (this.currentHistoryStepIndex === 0) {
      return undefined;
    }

    return this.historySteps[this.currentHistoryStepIndex].cursorStart;
  }
```

So there are two things needed a `VimState` and a `HistoryTracker`.
Is there already something like a `state` that stores information about the extension independent of the document? (I'm not experienced with vscode extensions yet).

And I guess that we have to adapt the HistoryTracker, also to implement `Goto previous buffer` and `Goto File`.

**Comment by 71** [comment]
That's a tricky one I haven't tried fixing yet. I started the work on this end in [history.ts](https://github.com/71/dance/blob/master/src/history.ts), but nothing has been made when it comes to storing the position of the last change. My first guess would be to modify [`Extension.setEditorMode`](https://github.com/71/dance/blob/ebe8556205b7a2ca1f0c6c13affd058914f1f628/src/extension.ts#L64) to save the current selections into the history tracker, and then use this information when the command is executed.

**Comment by geier1993** [comment]
Yay, that's what I was looking for.
Now we have to extend the HistoryTracker and store all Selections per Mode-Switch in a List for each Document.... sounds not tooo difficult.

But with that we should provide a mechanism to clear all the history and add configuration options on history management (i.e. maximal history size cache (or no limit), maximal number of history elements (or no limit), store in temporal file? somewhere in the future...) 
That's tough though.

**Comment by 71** [comment]
## Storing
My plan here was to leave history handling to VS Code, and to only track things when we need to do so (eg. changes in `insert` mode while in a macro, saving positions before / after edits, etc). If in your experience Kakoune's history behavior is much better than VS Code's, we sure can try to emulate it (but preferably as an optional feature).

In any case, for now I simply thought we could store everything in a list, and only keep the last N elements, where N could be 100 or 1000. The user could change that number in the settings.

## Extension settings
Extension settings are defined in [`package.ts`](https://github.com/71/dance/blob/5b2688149866e9e3a42f2673ef1e807859336771/package.ts#L71-L75), but currently there are no utilities to read those settings (you can see an example of reading the `dance.enabled` setting [here](https://github.com/71/dance/blob/5b2688149866e9e3a42f2673ef1e807859336771/src/extension.ts#L127)).

Since `package.ts` generates some files automatically, it would be trivial to also generate a `settings.ts` file with specific functions for getting / updating each setting we make available.

**Comment by geier1993** [comment]
> My plan here was to leave history handling to VS Code, and to only track things when we need to do so (eg. changes in insert mode while in a macro, saving positions before / after edits, etc). If in your experience Kakoune's history behavior is much better than VS Code's, we sure can try to emulate it (but preferably as an optional feature).

I thought about it from a less dreamy point of view and came to another  Point.
The implementation of saving and restoring selections is still missing, but an important feature for me.
Another point is insertion. In kakoune the on inserting text, the previously selected text remains selected. In VSCode we have to collapse the selection, otherwise VSCode is replacing text.
In relation to save & restore selections, a feature that is automatically restoring the selections I made would be very helpful. (May also be configurable by some apropriate setting).

And furthermore in relation to the goto command, both commands use `.` as a special register and in fact, the goto command is nothing more then restoring the last selection and reducing it, therefore I would implement the mark feature first.

Now to my concerns, by storing selections we have to track document changes and  update all selections according to TexDocumentContentChangeEvents (i.e. be ordering and accumulating the ranges and applying them on all selection registers).
This mechanism would also update the Selections saved before the insertion took place and put it to the history.

**Comment by 71** [comment]
> In kakoune the on inserting text, the previously selected text remains selected.

I actually noticed that for the first time yesterday! It's something we can probably emulate without too much work using [decorations](https://code.visualstudio.com/api/references/vscode-api#TextEditor.setDecorations).

> Now to my concerns, by storing selections we have to track document changes and update all selections according to TexDocumentContentChangeEvents (i.e. be ordering and accumulating the ranges and applying them on all selection registers).
This mechanism would also update the Selections saved before the insertion took place and put it to the history.

I have started tracking changes [here](https://github.com/71/dance/blob/5b2688149866e9e3a42f2673ef1e807859336771/src/history.ts#L14) and [here](https://github.com/71/dance/blob/5b2688149866e9e3a42f2673ef1e807859336771/src/extension.ts#L148) (which is redundant, I should only do it once), but I'm not doing anything with that information yet.

**Comment by geier1993** [comment]
The decorations work very well. 
However processing the changes is still an issue.
It took me some time to understand `TextDocumentContentChange` but It should be possible:

* On Insertion the `change.rangeLength` is 0 that means `change.range.start` equals `change.range.end`. Using `change.text.length` we get information of new inserted text. The number of lines inserted can be computed by `(chang.text.match(/o/g)||[]).length` and even better,
with `document.positionAt(change.rangeOffset + change.text.length)` we can compute the range of new inserted text exactly (and very cheap).

* On deletion the behaviour is even simpler because `change.range` gives all information

* In general that means that we can store selections and apply range changes incrementally. The result should be exact.
  ("i.e. to build a register")

* On using undo/redo a ChangeEvent is fired - so we do not need to save any history and just have to handle the incremental changes (Yay, thas super cool - very lightweight)

* For Comparison: I've looked how [vscodevim](https://github.com/VSCodeVim/Vim/blob/master/src/history/historyTracker.ts#L383) is implementing Marks and changes. Currently the make a diff on the whole document! That is super ineffective... So I think we can do better

* One Problem that I have noticed:
  On changing the mode an event with text "on"/"relative" is fired. This happens because of changing the lineNumber configuration... But I have no Idea why it triggers a text change event.
The Range Information is always the same i.e. `(1, 26) to (1, 36)), length: 10, offset: 28, text: "on")]` at least on my linux machine...
  However, we could create a function `Extension.isModeChanging` and control it in the function `Extension.onActiveModeChanged` (here the lineNumber configuration is set...)...
  Then in the handleChange function we can filter these erroneous events.
 A bit hacky but It should work.
 I am just worrying about interaction with other extensions.

**Comment by yuchenshi** [comment]
FYI `g.` now works in 0.3.0. Let's track the other half of the issue.

**Comment by 71** [comment]
Note: with Dance 0.5, tracking selections is possible. However, the `insert` mode selections are not tracked by default, so `goto last modification` is implemented slightly differently (it is flawed, since changes to the document via Dance commands above the last modification will not update its offset).

**Comment by 71** [comment]
I ended up re-implementing this by saving selections when entering `insert` mode, and having `g.` restoring them. It's just easier to do and cleaner, and I doubt we'll need much more complicated than that.

**Comment by tylerlaprade** [comment]
FWIW, ⌘ `kq` goes to the last edit location globally across all files, which is slightly different but might be useful to anyone who is searching for that functionality and finds this issue.
