### ISSUE TITLE
Cursor Style doesn't always match mode when changing tabs

### ISSUE THREAD

**Issue by Mcmartelle** [71/dance#71]
**Environment:**
macOS Mojave Version 10.14.6 (18G3020)
VSCode Version: 1.43.0
Dance Version: 0.2.2

**Steps To Reproduce:**
1. Set `Dance>Insert Mode: Cursor Style` to `line` and set `Dance>Normal Mode: Cursor Style` to `block`.
2. Open 2 files.
3. In file 1 press `i` to enter Insert Mode.
4. Change tabs to file 2 which is still in Normal Mode.

**Expected Result:**
The cursor style should be the `block` style, matching Normal Mode.

**Actual Result:**
The cursor style is the `line` style, which doesn't match the mode for that file.

![cursor-style](https://user-images.githubusercontent.com/15348850/76714988-6ec36880-66e7-11ea-990b-0e4eaeceb7c4.gif)

*Edit: Added environment.

**Comment by 71** [comment]
This is now fixed in `unstable`: e058cdb6ecd988194837cfffff8f3702cd5d9e4d.
