### ISSUE TITLE
Hitting `<esc>` when accidentally hitting `r` does not escape out of replace mode

### ISSUE THREAD

**Issue by timjs** [71/dance#79]
To reproduce:
* Hit `r`
* Hit `<esc>`
* Hit `l`

Expected:
* Dance escapes to normal mode and moves cursor to the right

Actual:
* Dance replaces current selection with `l` character

**Comment by 71** [comment]
Fixed in `unstable`: 548469490a918019cf74b8e03e429aa84697e264.
