### ISSUE TITLE
Behavior of `j`/`J`

### ISSUE THREAD

**Issue by grtlr** [71/dance#9]
Thanks for publishing the extension to the marketplace, it's working great!

One thing I noticed is that the behavior of `j`/`J` seems to have changed from regular Kakoune. As far as I can tell, in regular Kakoune `j` acts similar to the arrow key: it only performs movements, while `J` can be used to extend a selection. 

In _dance_ `j` extends the selection, where as `J` goes into _insert mode_. Is this intentional, or maybe something that I can configure?

**Comment by 71** [comment]
This seems like a bug. I'm on it.

**Comment by grtlr** [comment]
Awesome, thanks!
