### ISSUE TITLE
Allow case-insensitive match for goto selection

### ISSUE THREAD

**Issue by vbn** [71/dance#95]
In `kakoune`, the `goto` commands allow case-insensitive selection. For e.g. command for jumping to start of the buffer is `gk` or `gK`. It's especially useful when extending selection with `Gk` or `GK`. So there is no need to release the `Shift` key when typing the command.

One hacky way to fix this would be to duplicate the commands in the `jumps` array in `goto.ts` [here](https://github.com/71/dance/blob/master/src/commands/goto.ts#L10).

I believe there should be a much cleaner way to fix this by tweaking `promptInList` with an extra flag.

Other commands still need the current case-sensitive match behavior. For e.g. `<a-i>`.

**Comment by 71** [comment]
Oh, you're right. A trivial solution would be to have `promptInList` be case insensitive iff all keys have the same casing, but it won't work with symbols (e.g `.` needs shift on Azerty, but not on Qwerty).

Another solution would to allow multiple keys in `dance.menus`, or a `caseInsensitive` option. Again, though, I don't know how this option would work with symbols.

**Comment by yuchenshi** [comment]
FYI, a better workaround is possible now via the `dance.menus` setting on master. It still requires duplicating all items, but at least should not require modifying the source code.

**Comment by yuchenshi** [comment]
I personally use the snippet below in my `settings.json` with 0.3.0 and so far it works great:

```json
    "dance.menus": {
      "goto": {
        "items": {
          // Make uppercase extend.
          "H": {
            "text": "extend to line start",
            "command": "dance.goto.lineStart.extend"
          },
          "L": {
            "text": "extend to line end",
            "command": "dance.goto.lineEnd.extend"
          },
          "I": {
            "text": "extend to non-blank line start",
            "command": "dance.goto.lineStart.nonBlank.extend"
          },
          "G": {
            "text": "extend to first line",
            "command": "dance.goto.firstLine.extend"
          },
          "K": {
            "text": "extend to first line",
            "command": "dance.goto.firstLine.extend"
          },
          "J": {
            "text": "extend to last line",
            "command": "dance.goto.lastLine.extend"
          },
          "E": {
            "text": "extend to last char of last line",
            "command": "dance.goto.lastCharacter.extend"
          },
          "T": {
            "text": "extend to the first displayed line",
            "command": "dance.goto.firstVisibleLine.extend"
          },
          "C": {
            "text": "extend to the middle displayed line",
            "command": "dance.goto.middleVisibleLine.extend"
          },
          "B": {
            "text": "extend to the last displayed line",
            "command": "dance.goto.lastVisibleLine.extend"
          },
        },
      },
    }
```

Just note that due to the number of items, it probably won't fit in one screen in the prompt menu when you press `g`. (You may have to scroll down to see those items.) But it works regardless.

I've intentionally left out `f` since I don't think "extending to file" is a thing you can do. If you feel strongly about `shift+.`, you can also put `>` in there for Qwerty. I have zero idea what makes sense on Azerty.

I think now the question for @vbn and @71: Given that there is a way to accomplish this in user settings, do we still want some support in the extension itself? I personally think we should leave it there since it's subject to personal preferences and user settings are much customizable.

**Comment by 71** [comment]
@yuchenshi I think @vbn's goal is to have both e.g `A` and `a` perform the same action (`g` selects whereas `G` extends).

I do agree, the current features are enough. Also, you can group keybindings together by typing e.g. "Aa" as a key of `items`. This will reduce the number of items both in the user settings and in the goto menu.
